import { Pillar } from '../types'

export const pillars: Pillar[] = [
  {
    id: 'milk',
    name: 'Breastfeeding',
    icon: '🍼',
    description: 'Everything about breastfeeding and infant formulas.',
    color: '#F9A8D4',
    intro: 'Feeding your little one, dear, is the first conversation you two will have. Whether you breastfeed, formula-feed, or mix both, the goal is the same: a fed, content baby and a mother who isn\'t running on empty. The WHO recommends exclusive breastfeeding for the first 6 months, but every family\'s story is different and all of them are valid.',
    tips: [
      { label: 'On demand', text: 'Offer the breast whenever the baby shows signs of hunger — rooting, hands to mouth, smacking lips — without a fixed schedule. Crying is a late hunger cue.' },
      { label: 'Proper latch', text: 'The baby\'s mouth should cover most of the areola, not just the nipple, with lips flanged outward like a fish. A shallow latch is the number one cause of sore nipples.' },
      { label: 'Hydration', text: 'Drink a tall glass of water every time you sit down to nurse. Milk is about 87% water and your body will tell you with thirst and headaches if you\'re behind.' },
      { label: 'Cluster feeding', text: 'Newborns often nurse every hour in the evening — this is normal and helps boost your supply, not a sign of low milk. It usually peaks at 2-3 weeks and again around 6 weeks.' },
      { label: 'Wet diaper count', text: 'After day 5, expect at least 6 wet diapers and 3-4 yellow seedy stools per day. This is your most reliable sign that baby is getting enough milk.' },
      { label: 'Formula is not failure', text: 'Combination feeding or full formula is a safe, nourishing choice. Modern formulas are nutritionally complete — what matters is that your baby is fed and you are well.' },
      { label: 'Storing milk', text: 'Freshly pumped milk keeps 4 hours at room temperature, 4 days in the fridge, and 6 months in a regular freezer. Label every bag with the date.' },
      { label: 'When to call a lactation consultant', text: 'Persistent pain past the first 10 seconds of latch, cracked nipples, weight loss greater than 10% of birth weight, or fewer than 6 wet diapers a day all warrant a same-week appointment.' },
      { label: 'Mastitis warning signs', text: 'A red, hot, painful wedge on the breast with fever and body aches is mastitis. Keep nursing on that side, apply cold compresses between feeds, and call your doctor — antibiotics are often needed.' },
    ],
    suggestions: [
      'My 2-month-old nurses every hour, is that normal?',
      'How do I know if my breast milk is enough?',
      'When should I introduce formula?',
      'How do I store breast milk properly?',
    ],
  },
  {
    id: 'food',
    name: 'Feeding',
    icon: '🥑',
    description: 'Introducing solids, meal plans, and tips for every stage.',
    color: '#86EFAC',
    intro: 'Solids are an adventure, dear — not a replacement for milk in the first year, but the start of a lifelong relationship with food. The goal between 6 and 12 months is exposure and texture, not calories; after 12 months it shifts to variety, balance, and joining the family table.',
    tips: [
      { label: 'BLW', text: 'From 6 months on, offer soft finger foods the size of your pinky so the baby can explore textures and self-feed. Look for the readiness signs: sitting unsupported, lost tongue-thrust reflex, and interest in your plate.' },
      { label: 'No salt or sugar', text: 'Avoid added salt and sugar in your baby\'s food until age 2 — their kidneys can\'t process sodium and added sugar trains a sweet tooth for life. Honey is off-limits before 12 months due to botulism risk.' },
      { label: 'Variety', text: 'Introduce a new single-ingredient food every 2-3 days during the first weeks to identify possible allergies. After that, mix freely.' },
      { label: 'Top 9 allergens early', text: 'Current AAP guidance is to introduce peanut, egg, dairy, wheat, soy, tree nuts, fish, shellfish, and sesame between 4-6 months — early exposure reduces allergy risk.' },
      { label: 'Gag is not choke', text: 'Gagging is loud, red-faced, and protective — let baby work through it. Choking is silent, blue, and needs immediate action. Learn infant CPR before starting solids.' },
      { label: 'Picky toddler phase', text: 'Around 18-24 months neophobia kicks in and the same child who ate broccoli last month refuses it. Keep offering without pressure — it takes 10-15 exposures for a new food to feel familiar.' },
      { label: 'Division of responsibility', text: 'You decide what, when, and where; your child decides whether and how much. Forcing one more bite backfires and creates food anxiety.' },
      { label: 'Iron-rich first foods', text: 'Babies are born with iron stores that deplete around 6 months. Start with iron-fortified cereal, pureed meat, lentils, or beans rather than only rice and fruit.' },
      { label: 'Foods to avoid under 4', text: 'Whole grapes, whole nuts, popcorn, hard candy, hot dogs in coins, and chunks of raw apple or carrot are top choking hazards. Cut grapes lengthwise into quarters.' },
      { label: 'Sibling at the table', text: 'Toddlers eat better when they see older siblings or parents eating the same thing. Family meals — even just one a day — predict better eating habits at 10 years old.' },
    ],
    suggestions: [
      'What foods should I offer first when starting solids?',
      'My 1-year-old refuses vegetables, what can I do?',
      'How do I create a weekly meal plan for an 8-month-old?',
      'Which fruits are best to start with?',
    ],
  },
  {
    id: 'nutrition',
    name: 'Nutrition',
    icon: '🧬',
    description: 'Vitamins, minerals, and infant supplementation.',
    color: '#FDE68A',
    intro: 'A child\'s body builds itself from the inside out in these first five years, sweetheart, and the small daily nutrients matter more than any single superfood. Most healthy children eating a varied diet don\'t need a multivitamin, but a few specific supplements are evidence-backed and worth knowing about.',
    tips: [
      { label: 'Vitamin D', text: 'The AAP recommends 400 IU of vitamin D daily for all breastfed and partially breastfed babies from the first days of life, continuing through childhood. Formula-fed babies need it once they drink less than 32 oz a day.' },
      { label: 'Iron', text: 'From 6 months on, include iron-rich foods like beans, red meat, lentils, and dark leafy greens at least once a day. Pair them with vitamin C foods (bell pepper, citrus, strawberries) to boost absorption.' },
      { label: 'Omega-3', text: 'Fatty fish like sardines and salmon are excellent sources of DHA for brain development. Aim for 2 servings of low-mercury fish per week from 12 months on.' },
      { label: 'Calcium after weaning', text: 'Once you wean, aim for 700 mg calcium daily (1-3 years): two cups of whole milk, fortified plant milk, yogurt, or cheese cover it easily.' },
      { label: 'Anemia screening', text: 'Pediatricians screen for iron-deficiency anemia between 9 and 12 months. Symptoms to watch for: pale skin, fatigue, poor appetite, and slow weight gain.' },
      { label: 'Whole milk vs. low-fat', text: 'Between 12 months and 2 years, give whole cow\'s milk — kids need the fat for brain growth. Switch to low-fat only after 2 unless your pediatrician advises otherwise.' },
      { label: 'Juice is not fruit', text: 'The AAP recommends no juice under 12 months and a max of 4 oz/day for 1-3 year olds. A whole orange has fiber and 4x less sugar concentration than juice.' },
      { label: 'Probiotics — when they help', text: 'Probiotics have solid evidence for antibiotic-associated diarrhea and infant colic (specifically L. reuteri), but routine daily use isn\'t needed for healthy kids.' },
      { label: 'Vegan and vegetarian kids', text: 'Plant-based diets can be healthy at any age but need planned B12, iron, zinc, and DHA. Work with a pediatric dietitian to avoid gaps in the first 2 years.' },
    ],
    suggestions: [
      'What vitamins does my baby need to take?',
      'How can I prevent anemia in the first year of life?',
      'Does my child need an omega-3 supplement?',
      'What is the correct vitamin D dose for a newborn?',
    ],
  },
  {
    id: 'vaccines',
    name: 'Vaccines',
    icon: '💉',
    description: 'Vaccination schedule, reactions, and post-vaccine guidance.',
    color: '#93C5FD',
    intro: 'Vaccines are one of the kindest gifts you give your child, love — not just protection for them, but for the babies in the waiting room who are too young to be immunized. The shots feel hard in the moment, but the diseases they prevent are harder.',
    tips: [
      { label: 'Stay on schedule', text: 'Follow the CDC/national vaccination calendar and don\'t delay doses unless medically necessary. Spaced-out schedules leave babies vulnerable for longer with no proven safety benefit.' },
      { label: 'Post-vaccine fever', text: 'A low-grade fever (under 102°F) and a sore, red injection site in the 24-48 hours after a shot are normal signs the immune system is working. Acetaminophen at weight-based dose is fine if baby is uncomfortable.' },
      { label: 'Shot record', text: 'Always bring the vaccination booklet to appointments and keep an updated photo on your phone — daycare, school, and the ER will all ask for it eventually.' },
      { label: 'Soothe the sting', text: 'Breastfeed or bottle-feed during the injection, hold baby skin-to-skin, and use slow firm pressure on the leg after. For older babies, a cold pack and distraction (bubbles, phone video) cut crying time in half.' },
      { label: 'When to call the doctor', text: 'Call within hours for: fever above 104°F, persistent crying longer than 3 hours, seizure, swelling larger than a tennis ball, or any sign of anaphylaxis (hives, swollen lips, trouble breathing).' },
      { label: 'Flu shot every year', text: 'From 6 months on, an annual flu vaccine cuts hospitalization risk by about 75% in young kids. October-November is ideal timing in the northern hemisphere.' },
      { label: 'The MMR-autism myth', text: 'The 1998 Wakefield paper was fraudulent and retracted. Dozens of studies covering millions of children show no link between MMR (or any vaccine) and autism. The schedule is safe.' },
      { label: 'Catch-up is possible', text: 'If you fell behind — moving, illness, a tough year — your pediatrician can build a catch-up schedule. Almost no dose is ever wasted; you usually don\'t have to start over.' },
      { label: 'Travel vaccines', text: 'If you\'re traveling internationally, check the CDC destination tool 6-8 weeks before departure. Yellow fever, hepatitis A, and typhoid may be needed depending on the country.' },
    ],
    suggestions: [
      'Which vaccines does my baby get at 2 months?',
      'Is it normal to have a fever after a vaccine?',
      'Can I delay a vaccine? What are the risks?',
      'Which optional vaccines are worth getting?',
    ],
  },
  {
    id: 'clothes',
    name: 'Layette',
    icon: '👶',
    description: 'Clothing, accessories, and organization for every season.',
    color: '#C4B5FD',
    intro: 'Dressing a tiny person is its own art form, dear — equal parts comfort, weather, and how many times that bodysuit is going to be peed on before lunch. Buy less than you think; babies grow through sizes faster than you can do laundry.',
    tips: [
      { label: 'Fabric', text: 'Choose 100% cotton, bamboo, or organic muslin to avoid irritation on newborn skin. Skip synthetics in the first months — they trap heat and can trigger rashes.' },
      { label: 'Layering', text: 'Dress the baby in one more light layer than what you\'re wearing as an adult. Check the back of the neck — if it\'s warm and dry, the temperature is right.' },
      { label: 'Sizing', text: 'Buy few newborn-size pieces — most babies outgrow them within 2-3 weeks, and some skip the size entirely. Stock up on 0-3 and 3-6 month instead.' },
      { label: 'Front-snap > over-the-head', text: 'In the first months, kimono-style and side-snap onesies save you wrestling a wobbly neck through a tight collar. Worth their weight in gold at 3 AM.' },
      { label: 'Sleep sack TOG', text: 'Wearable blankets are safer than loose blankets all the way through age 2. Use 0.5 TOG in summer rooms (74°F+), 1.0 TOG mild, 2.5 TOG cold (under 68°F).' },
      { label: 'Overheating risk', text: 'Overheating is linked to SIDS — the room should be 68-72°F. Never put a hat on a sleeping baby indoors and skip the puffy coat under car seat straps.' },
      { label: 'Wash before wearing', text: 'Always wash new clothes in fragrance-free detergent before first wear to remove finishing chemicals. Skip fabric softener for the first year.' },
      { label: 'Hand-me-downs are gold', text: 'Pre-washed cotton is softer, kinder to the planet, and free. Sleepers and bodysuits in good condition are perfect — only buy car seats and crib mattresses new.' },
      { label: 'Shoes are optional', text: 'Pre-walkers don\'t need shoes — soft socks or barefoot is better for foot development. When walking starts, look for flexible, wide-toe-box shoes you can bend in half.' },
    ],
    suggestions: [
      'How many clothes do I need for the layette?',
      'How do I dress the baby in summer without overheating?',
      'Which layette items are truly essential?',
      'What is the best fabric for newborn clothing?',
    ],
  },
  {
    id: 'recipes',
    name: 'Recipes',
    icon: '🍲',
    description: 'Practical and healthy recipes for every stage of your baby.',
    color: '#FDBA74',
    intro: 'Cooking for babies doesn\'t have to mean separate meals, sweetheart — most of what you already make can be adapted with a fork-mash or a knife. The kitchen is where children learn flavor, family, and that food is love, not battle.',
    tips: [
      { label: 'Homemade purees', text: 'Steam, then blend with breast milk, formula, or the cooking water for the right consistency. They\'re cheaper, more nutritious, and free of the preservatives in shelf-stable pouches.' },
      { label: 'Freezing', text: 'Freeze individual portions in silicone ice cube trays (1 oz cubes), then transfer to labeled freezer bags. Most purees keep 3 months frozen and thaw in 10 minutes in warm water.' },
      { label: 'Natural seasonings', text: 'Use garlic, onion, parsley, chives, cumin, cinnamon, dill, and a squeeze of lemon for flavor — babies\' palates love variety and they\'re less picky later. Skip salt until age 2.' },
      { label: 'Healthy fats', text: 'A drizzle of olive oil, a pat of unsalted butter, or a spoon of avocado on baby\'s meal boosts calories and helps absorb fat-soluble vitamins (A, D, E, K).' },
      { label: 'One-pot family meals', text: 'Lentil stew, chicken-and-rice soup, and roasted vegetables with pasta all work for the whole family. Pull baby\'s portion before adding salt for the adults.' },
      { label: 'Texture progression', text: 'Smooth puree at 6 months, mashed with lumps at 7-8 months, soft finger foods at 9-10 months, chopped table food by 12 months. Don\'t get stuck on smooth too long — it teaches chewing.' },
      { label: 'Smoothie hack for picky kids', text: 'Blend whole milk yogurt + frozen banana + spinach + nut butter for a stealth-vegetable breakfast. Use a straw cup so they don\'t see the green.' },
      { label: 'Snack ideas that aren\'t crackers', text: 'Cucumber spears with hummus, cheese cubes, hard-boiled egg, banana with almond butter, plain yogurt with berries. Protein + fat snacks hold blood sugar longer than carbs alone.' },
      { label: 'Toddler-friendly batch cooking', text: 'Sunday night, prep 3 base items (roasted sweet potato, shredded chicken, cooked quinoa) and mix-and-match through the week. Saves your sanity and reduces decision fatigue.' },
    ],
    suggestions: [
      'Puree recipe for a 6-month-old baby',
      'How do I make a nutritious soup for a baby?',
      'Healthy snack recipes for 2-year-olds',
      'How do I meal prep baby food for the whole week?',
    ],
  },
  {
    id: 'habits',
    name: 'Natural Care',
    icon: '🌿',
    description: 'Natural remedies, safe teas, and infant aromatherapy.',
    color: '#6EE7B7',
    intro: 'Natural doesn\'t always mean safe, dear — some of the gentlest-sounding plants are very strong for a baby\'s small body. Used wisely, alongside your pediatrician, herbs and routines can be lovely supports; used carelessly they can cause real harm.',
    tips: [
      { label: 'Chamomile', text: 'Weak chamomile tea can help calm a fussy baby, but only after 6 months and ideally with pediatrician guidance. Skip it entirely if there\'s a ragweed allergy in the family.' },
      { label: 'Lavender', text: 'A drop or two of properly diluted lavender essential oil in a warm bath may help with sleep from 6 months on. Never apply essential oils undiluted to skin and never give them orally.' },
      { label: 'Sunlight', text: '10-15 minutes of sunlight on arms and legs before 10 AM helps vitamin D synthesis and sets the circadian rhythm. Always use sunscreen on babies over 6 months after that window.' },
      { label: 'No honey under 1', text: 'Honey — raw, cooked, or in baked goods — can cause infant botulism in babies under 12 months. This includes "natural cough syrups" with honey.' },
      { label: 'Saline for stuffy noses', text: 'A few drops of saline solution followed by a bulb syringe or NoseFrida is the safest decongestant for any age. Over-the-counter cold meds are not recommended under 4.' },
      { label: 'Skip the gripe water', text: 'Most colic remedies (gripe water, fennel drops, anise tea) have weak evidence and some contain alcohol or sugar. The strongest evidence for colic is probiotic L. reuteri drops.' },
      { label: 'Bath as ritual', text: 'A warm bath 30-45 minutes before bed drops the core temperature on the way out and signals sleep. 2-3 baths a week is plenty under 1 year — daily bathing dries out skin.' },
      { label: 'Skin-to-skin past the newborn stage', text: 'Carrying your baby in a wrap or doing morning cuddles in pajamas regulates their nervous system, supports milk supply, and lowers cortisol well into the second year.' },
      { label: 'Essential oils to avoid', text: 'Peppermint, eucalyptus, rosemary, and camphor can slow breathing in babies under 2. Diffusers are safer than topical, but ventilate the room and never diffuse near a crib.' },
    ],
    suggestions: [
      'Which teas are safe for babies?',
      'Is aromatherapy safe for newborns?',
      'Natural remedies for baby colic',
      'How do I make an herbal bath for my baby?',
    ],
  },
  {
    id: 'medicine',
    name: 'Medicine',
    icon: '💊',
    description: 'Basic medicine cabinet, dosages, and when to see the pediatrician.',
    color: '#FCA5A5',
    intro: 'Knowing when to wait, when to call, and when to drive to the ER is one of the hardest skills of new parenting, love. A well-stocked medicine cabinet and your pediatrician\'s after-hours number are worth more than any internet search at 2 AM.',
    tips: [
      { label: 'Medicine cabinet', text: 'Keep at home: a digital thermometer, saline nasal spray, infant acetaminophen, infant ibuprofen (over 6 months), diaper rash cream with zinc oxide, oral rehydration solution, and a syringe-style medicine dispenser.' },
      { label: 'Self-medication', text: 'Never give a child a medication without pediatrician guidance, even common ones — dosing is weight-based and overdoses of acetaminophen and ibuprofen are a top cause of childhood liver and kidney injury.' },
      { label: 'Emergency fever rule', text: 'A rectal temperature of 100.4°F (38°C) or higher in a baby under 3 months is an automatic ER visit — even if baby looks fine. Their immune systems can\'t localize infection yet.' },
      { label: 'Acetaminophen dosing', text: 'Infant acetaminophen is 10-15 mg per kg every 4-6 hours, max 5 doses in 24 hours. The dropper that comes in the box is the only one you should use — household teaspoons vary wildly.' },
      { label: 'Ibuprofen, only after 6 months', text: 'Ibuprofen is 5-10 mg per kg every 6-8 hours and works longer than acetaminophen but isn\'t safe before 6 months or when there\'s vomiting/dehydration. Never alternate without a doctor\'s plan.' },
      { label: 'Cold meds are out', text: 'The FDA recommends no OTC cough and cold medicines for children under 4 — they don\'t work and have caused fatal overdoses. Humidifier, saline, honey (over 1), and patience are the treatment.' },
      { label: 'When to head to the ER', text: 'Trouble breathing or grunting, blue lips, seizure, stiff neck with fever, dehydration (no wet diaper in 8 hours), severe abdominal pain, head injury with vomiting, or a baby who can\'t be roused.' },
      { label: 'Antibiotics aren\'t for viruses', text: 'Most coughs, runny noses, and sore throats are viral and don\'t respond to antibiotics. Asking for them "just in case" raises resistance and disrupts gut flora — trust your pediatrician\'s assessment.' },
      { label: 'Poison control', text: 'Save 1-800-222-1222 (US Poison Control) in your phone now, before you need it. They answer 24/7 in 150+ languages and can usually tell you whether you need the ER.' },
      { label: 'Medication storage', text: 'Lock medications, vitamins, and supplements up high or in a child-resistant box. Toddler ER visits for medication ingestion peak between 18 and 30 months — gummy vitamins look like candy.' },
    ],
    suggestions: [
      'What antipyretic can I give my baby?',
      'How do I calculate medicine dosage by weight?',
      'When should I take my child to the emergency room?',
      'What should I have in the baby medicine cabinet?',
    ],
  },
  {
    id: 'milestones',
    name: 'Milestones',
    icon: '⭐',
    description: 'Track developmental milestones and celebrate firsts.',
    color: '#67E8F9',
    intro: 'Milestones are signposts, sweetheart, not a race — they tell us a child\'s brain and body are doing what they should, in roughly the right order. The range of "normal" is wider than most parenting books admit, but knowing the limits helps you catch the small things early.',
    tips: [
      { label: 'Every child is unique', text: 'Milestones are guidelines, not deadlines. The CDC ranges (e.g. "walks by 18 months") are the upper edge of normal — most kids walk much earlier.' },
      { label: 'First words', text: 'Most babies say their first true word between 10-14 months and have 5-20 words by 18 months. Babbling, pointing, and following simple instructions all count as language and predict speech.' },
      { label: 'Motor skills start at day one', text: 'Tummy time from the first week — even 1 minute at a time — builds the neck, shoulder, and core strength needed for rolling, sitting, crawling, and walking. Aim for 30 minutes total a day by 3 months.' },
      { label: 'Social smile at 6-8 weeks', text: 'A genuine social smile in response to your face (not gas) is one of the earliest social milestones. No social smile by 3 months is worth mentioning to the pediatrician.' },
      { label: 'Object permanence at 8 months', text: 'When babies start looking for a toy you hide under a blanket, their brain has learned that things exist when out of sight. This is also when separation anxiety often kicks in — it\'s a developmental win, not regression.' },
      { label: 'Red flags worth a same-week call', text: 'No eye contact by 3 months, no babbling by 9 months, no pointing or waving by 12 months, no single words by 16 months, loss of any skill at any age — early intervention works best before age 3.' },
      { label: 'Walking range is huge', text: '9-18 months is all normal. Bum-shufflers and late walkers (15-17 months) often skip crawling entirely and are usually neurotypical — but mention it at the 15-month checkup just in case.' },
      { label: 'Two-word phrases by 24 months', text: 'By the second birthday, expect roughly 50 words and 2-word combinations ("more milk", "daddy go"). If not, ask about a speech-language evaluation — they\'re free in most regions.' },
      { label: 'Pretend play around 18-24 months', text: 'Feeding a doll, talking on a banana, putting teddy to bed — pretend play is a major cognitive and social milestone. It also predicts later language and emotional regulation.' },
      { label: 'Don\'t compare siblings', text: 'Birth order changes the milestone landscape — second children often talk later (older sibling speaks for them) but walk earlier (chasing them). Each child gets their own timeline.' },
    ],
    suggestions: [
      'What milestones should my 6-month-old be hitting?',
      'My baby is 14 months and not walking yet — is that normal?',
      'When do babies start talking in sentences?',
      'How can I encourage my baby to crawl?',
    ],
  },
]
