import type { Pillar } from '../types'

export const pregnancyPillars: Pillar[] = [
  {
    id: 'week-by-week',
    name: 'Week by Week',
    icon: '📅',
    description: 'Baby development, what to expect each week, and how your body is changing.',
    color: '#93C5FD',
    tips: [
      { label: 'First trimester', text: 'Weeks 1-12: All major organs begin forming. Fatigue and nausea are common — rest when you can.' },
      { label: 'Second trimester', text: 'Weeks 13-26: Energy returns, baby kicks start. Best time for nursery planning and babymoon.' },
      { label: 'Third trimester', text: 'Weeks 27-40: Baby gains weight rapidly. Practice breathing exercises and finalize your birth plan.' },
    ],
    suggestions: [
      'What is my baby doing at this stage?',
      'What body changes should I expect this week?',
      'Is my baby\'s size normal for this week?',
      'What milestones happen this trimester?',
    ],
  },
  {
    id: 'symptoms-relief',
    name: 'Symptoms & Relief',
    icon: '🩹',
    description: 'Managing nausea, back pain, swelling, and other pregnancy symptoms.',
    color: '#FCA5A5',
    tips: [
      { label: 'Morning sickness', text: 'Eat small, frequent meals. Ginger tea and crackers before getting out of bed can help.' },
      { label: 'Back pain', text: 'Use a pregnancy pillow, practice prenatal yoga, and avoid standing for long periods.' },
      { label: 'Swelling', text: 'Elevate your feet, stay hydrated, and reduce salt intake. Call your doctor if swelling is sudden or severe.' },
    ],
    suggestions: [
      'How can I relieve morning sickness naturally?',
      'Is it normal to have back pain at this stage?',
      'What helps with pregnancy insomnia?',
      'When should I worry about swelling?',
    ],
  },
  {
    id: 'birth-planning',
    name: 'Birth Planning',
    icon: '🏥',
    description: 'Birth types, hospital bag, labor positions, and creating your birth plan.',
    color: '#C4B5FD',
    tips: [
      { label: 'Birth plan', text: 'Write your preferences for labor — pain management, positions, who will be in the room. Share it with your OB.' },
      { label: 'Hospital bag', text: 'Pack by week 36: comfy clothes, nursing bra, baby outfit, phone charger, snacks, and your birth plan.' },
      { label: 'Labor signs', text: 'Regular contractions, water breaking, bloody show, and lower back pain are signs labor is starting.' },
    ],
    suggestions: [
      'What should I include in my birth plan?',
      'What\'s the difference between natural and medicated birth?',
      'When should I go to the hospital?',
      'What should I pack in my hospital bag?',
    ],
  },
  {
    id: 'breastfeeding-prep',
    name: 'Breastfeeding Prep',
    icon: '🤱',
    description: 'Preparing for breastfeeding — education, equipment, and what to expect.',
    color: '#F9A8D4',
    tips: [
      { label: 'Colostrum', text: 'Your first milk (colostrum) is liquid gold — packed with antibodies. Baby only needs tiny amounts in the first days.' },
      { label: 'Equipment', text: 'Consider a breast pump, nursing pads, nipple cream, and nursing-friendly clothes before baby arrives.' },
      { label: 'Latch practice', text: 'Watch videos and consider a lactation consultant. A good latch prevents pain and ensures baby gets enough milk.' },
    ],
    suggestions: [
      'How do I prepare for breastfeeding before birth?',
      'What breast pump should I get?',
      'What is colostrum and when does it come?',
      'How do I know if breastfeeding is going well?',
    ],
  },
  {
    id: 'baby-gear',
    name: 'Baby Gear',
    icon: '🍼',
    description: 'Essential items, nursery setup, and what you actually need vs. marketing hype.',
    color: '#FDBA74',
    tips: [
      { label: 'Essentials only', text: 'Crib, car seat, diapers, onesies, and a few blankets. Skip the fancy gadgets — babies need very little.' },
      { label: 'Safety first', text: 'Bare crib (no pillows, bumpers, toys). Car seat installed and inspected before due date.' },
      { label: 'Second-hand', text: 'Clothes, toys, and furniture can be second-hand. Car seats should be new or from a trusted source with no recall history.' },
    ],
    suggestions: [
      'What baby gear do I actually need?',
      'How do I set up a safe nursery?',
      'What car seat is best for a newborn?',
      'What can I buy second-hand safely?',
    ],
  },
  {
    id: 'partner-support',
    name: 'Partner Support',
    icon: '💑',
    description: 'How partners can actively support during pregnancy, labor, and postpartum.',
    color: '#86EFAC',
    tips: [
      { label: 'Be present', text: 'Attend appointments, ask questions, and show interest in baby\'s development. Your partner needs emotional support too.' },
      { label: 'Practical help', text: 'Take on more household tasks, cook meals, and help with nursery setup. Small acts matter enormously.' },
      { label: 'Birth support', text: 'Learn about labor stages, practice breathing together, and know the birth plan so you can advocate during delivery.' },
    ],
    suggestions: [
      'How can my partner support me during pregnancy?',
      'What role does the partner play during labor?',
      'How do we prepare as a team for the baby?',
      'What should partners know about postpartum?',
    ],
  },
  {
    id: 'postpartum-prep',
    name: 'Postpartum Prep',
    icon: '🌙',
    description: 'What to expect after birth — recovery, emotions, and the fourth trimester.',
    color: '#FDE68A',
    tips: [
      { label: 'Recovery takes time', text: 'Your body needs 6-8 weeks minimum to recover. Accept help, rest when baby sleeps, and be gentle with yourself.' },
      { label: 'Baby blues vs. PPD', text: 'Feeling emotional in the first 2 weeks is normal. If sadness, anxiety, or numbness persist beyond that, talk to your doctor.' },
      { label: 'Meal prep now', text: 'Freeze meals before birth. You won\'t want to cook with a newborn. Accept every meal offer from friends and family.' },
    ],
    suggestions: [
      'How long does postpartum recovery take?',
      'What\'s the difference between baby blues and postpartum depression?',
      'How do I prepare for the first weeks at home?',
      'What postpartum supplies should I buy now?',
    ],
  },
  {
    id: 'pregnancy-nutrition',
    name: 'Nutrition',
    icon: '🥗',
    description: 'What to eat, what to avoid, and supplements for each trimester.',
    color: '#86EFAC',
    tips: [
      { label: 'Folic acid', text: 'Take 400-800mcg daily from before conception through the first trimester. Critical for neural tube development.' },
      { label: 'Avoid', text: 'Raw fish, unpasteurized cheese, deli meats, high-mercury fish, alcohol, and excess caffeine (limit 200mg/day).' },
      { label: 'Iron-rich foods', text: 'Your blood volume increases 50%. Eat red meat, spinach, lentils, and pair with vitamin C for better absorption.' },
    ],
    suggestions: [
      'What foods should I avoid during pregnancy?',
      'What supplements do I need this trimester?',
      'How much water should I drink while pregnant?',
      'Can I eat sushi during pregnancy?',
    ],
  },
  {
    id: 'emotional-wellness',
    name: 'Emotional Wellness',
    icon: '🧘',
    description: 'Managing anxiety, mood swings, and building emotional resilience.',
    color: '#67E8F9',
    tips: [
      { label: 'Mood swings are normal', text: 'Hormones cause emotional ups and downs. Talk to your partner, journal, and don\'t judge yourself for feeling overwhelmed.' },
      { label: 'Anxiety', text: 'Some worry about baby\'s health is normal. If anxiety is consuming your thoughts or affecting sleep, seek professional support.' },
      { label: 'Self-care', text: 'Prenatal yoga, walks in nature, warm baths, and connecting with other expecting parents can all help.' },
    ],
    suggestions: [
      'Is it normal to feel anxious during pregnancy?',
      'How can I manage pregnancy mood swings?',
      'What relaxation techniques are safe during pregnancy?',
      'When should I seek help for prenatal anxiety?',
    ],
  },
]
