import type { Pillar } from '../types'

export const pregnancyPillars: Pillar[] = [
  {
    id: 'week-by-week',
    name: 'Week by Week',
    icon: '📅',
    description: 'Baby development, what to expect each week, and how your body is changing.',
    color: '#93C5FD',
    intro: 'Every week your little one is doing something new, dear — from a poppy seed at week 4 to a watermelon by week 40. Tracking the journey week by week helps you understand both baby\'s growth and the changes happening in your own body.',
    tips: [
      { label: 'First trimester', text: 'Weeks 1-12: All major organs begin forming. Fatigue and nausea are common — rest when you can and don\'t push through exhaustion.' },
      { label: 'Second trimester', text: 'Weeks 13-26: Energy returns and baby kicks start around weeks 18-22. This is the best window for nursery planning and a babymoon.' },
      { label: 'Third trimester', text: 'Weeks 27-40: Baby gains roughly half a pound a week. Practice breathing exercises and finalize your birth plan by week 36.' },
      { label: 'First kicks', text: 'You\'ll feel flutters between weeks 16 and 25 — earlier for second-time moms. Track patterns starting around week 28.' },
      { label: 'Anatomy scan', text: 'The big ultrasound happens between weeks 18-22, checking organs, spine, and (if you want to know) baby\'s sex.' },
      { label: 'Viability milestone', text: 'At 24 weeks baby reaches viability, meaning survival outside the womb becomes possible with medical support. A reassuring milestone.' },
      { label: 'Lightening', text: 'In the last weeks baby drops into the pelvis — you\'ll breathe easier but pee constantly. First-time moms feel it 2-4 weeks before labor.' },
      { label: 'Bump measurements', text: 'From week 20 onward, your fundal height in centimeters roughly matches your weeks. Your OB will measure at every visit.' },
      { label: 'Full term defined', text: 'Forty weeks is the average but full term is 37-42 weeks. Only about 5% of babies arrive on their actual due date.' },
    ],
    suggestions: [
      'What is my baby doing at this stage?',
      'What body changes should I expect this week?',
      'Is my baby\'s size normal for this week?',
      'What milestones happen this trimester?',
    ],
  },
  {
    id: 'symptoms-relief',
    name: 'Symptoms & Relief',
    icon: '🩹',
    description: 'Managing nausea, back pain, swelling, and other pregnancy symptoms.',
    color: '#FCA5A5',
    intro: 'Pregnancy symptoms come in waves, love, and most have surprisingly simple remedies. Knowing what\'s normal versus what needs a phone call to your doctor will save you a lot of late-night worry.',
    tips: [
      { label: 'Morning sickness', text: 'Eat small, frequent meals every 2-3 hours. Ginger tea, vitamin B6, and crackers before getting out of bed all help calm the queasiness.' },
      { label: 'Back pain', text: 'Use a pregnancy pillow between your knees, practice prenatal yoga, and avoid standing for long stretches. A maternity support belt helps after week 24.' },
      { label: 'Swelling', text: 'Elevate your feet, stay hydrated, and reduce salt intake. Call your doctor if swelling is sudden, asymmetric, or paired with headache — it can signal preeclampsia.' },
      { label: 'Heartburn', text: 'Sleep propped on pillows, avoid spicy and fatty foods after 6pm, and try Tums (calcium carbonate) which is safe and doubles as calcium.' },
      { label: 'Round ligament pain', text: 'Sharp twinges on the sides of your belly in the second trimester are your ligaments stretching. Move slowly when you change positions.' },
      { label: 'Pregnancy insomnia', text: 'Side-sleeping (preferably left) improves blood flow to baby. A pregnancy pillow, cool room, and screens off an hour before bed make a real difference.' },
      { label: 'When to call', text: 'Severe headache, blurred vision, vaginal bleeding, fever over 38°C, decreased fetal movement after week 28, or contractions before 37 weeks — call immediately.' },
      { label: 'Hemorrhoid relief', text: 'Common in the third trimester from pressure on pelvic veins. Witch hazel pads, fiber, hydration, and not straining on the toilet all help.' },
      { label: 'Leg cramps', text: 'Often hit at night in the second half of pregnancy. Stretch your calves before bed, stay hydrated, and ask your doctor about magnesium.' },
    ],
    suggestions: [
      'How can I relieve morning sickness naturally?',
      'Is it normal to have back pain at this stage?',
      'What helps with pregnancy insomnia?',
      'When should I worry about swelling?',
    ],
  },
  {
    id: 'birth-planning',
    name: 'Birth Planning',
    icon: '🏥',
    description: 'Birth types, hospital bag, labor positions, and creating your birth plan.',
    color: '#C4B5FD',
    intro: 'A birth plan is less a script and more a compass, sweetheart — it tells your team what matters to you when things move fast. The best plans are flexible, one page long, and shared with everyone who\'ll be in the room.',
    tips: [
      { label: 'Birth plan', text: 'Write your preferences for labor — pain management, positions, who will be in the room, and immediate-newborn wishes like skin-to-skin. Share it with your OB by week 32.' },
      { label: 'Hospital bag', text: 'Pack by week 36: comfy clothes, nursing bra, lip balm, baby outfit, phone charger, snacks, and your birth plan. Have a bag for partner too.' },
      { label: 'Labor signs', text: 'Regular contractions getting stronger, water breaking, bloody show, and persistent lower back pain are signs labor is starting. Time contractions when they begin.' },
      { label: 'The 5-1-1 rule', text: 'Head to the hospital when contractions are 5 minutes apart, lasting 1 minute, for 1 hour straight — unless your water breaks or you\'re bleeding.' },
      { label: 'Pain options', text: 'Epidurals, nitrous oxide, IV meds, hypnobirthing, water immersion, and TENS units all exist. Decide what you\'re open to but stay flexible.' },
      { label: 'Labor positions', text: 'Upright positions — squatting, hands-and-knees, birthing ball — use gravity and widen the pelvis. Lying flat on your back is the hardest position.' },
      { label: 'C-section reality', text: 'About 30% of births in the US are cesarean. Recovery is 6 weeks, not 2 — pack high-waisted underwear and arrange help with stairs.' },
      { label: 'VBAC option', text: 'If you\'ve had a previous c-section, ask about VBAC (vaginal birth after cesarean). Success rates are 60-80% with the right candidate and provider.' },
      { label: 'Postpartum hospital', text: 'Most stays are 1-2 nights for vaginal, 3-4 for c-section. Use that time — ask every nurse to show you a feeding hold or a swaddle.' },
    ],
    suggestions: [
      'What should I include in my birth plan?',
      'What\'s the difference between natural and medicated birth?',
      'When should I go to the hospital?',
      'What should I pack in my hospital bag?',
    ],
  },
  {
    id: 'breastfeeding-prep',
    name: 'Breastfeeding Prep',
    icon: '🤱',
    description: 'Preparing for breastfeeding — education, equipment, and what to expect.',
    color: '#F9A8D4',
    intro: 'Breastfeeding is natural, dear, but that doesn\'t mean it\'s easy at first — most moms hit a learning curve in the first two weeks. A bit of prep before baby arrives makes those early latch attempts far less stressful.',
    tips: [
      { label: 'Colostrum', text: 'Your first milk (colostrum) is liquid gold — packed with antibodies. Baby\'s stomach is the size of a cherry at birth, so tiny amounts are enough.' },
      { label: 'Equipment', text: 'Consider a breast pump (often free through insurance in the US), nursing pads, lanolin or nipple cream, and 2-3 nursing bras before baby arrives.' },
      { label: 'Latch practice', text: 'Watch videos and book a prenatal lactation consult if possible. A deep latch — mouth covering the areola, not just the nipple — prevents pain.' },
      { label: 'Milk comes in', text: 'Mature milk replaces colostrum around days 3-5. Your breasts may feel rock-hard for 24-48 hours — frequent nursing and cool cabbage leaves help.' },
      { label: 'Feed on demand', text: 'Newborns nurse 8-12 times in 24 hours, sometimes cluster-feeding for hours. This is normal and builds your supply for the months ahead.' },
      { label: 'Pumping basics', text: 'If you\'re returning to work, start introducing a bottle around weeks 4-6 to avoid bottle refusal. Begin building a freezer stash 2-3 weeks before going back.' },
      { label: 'Common myths', text: 'Small breasts make plenty of milk. Beer doesn\'t boost supply. And nipple shape almost never prevents breastfeeding with the right support.' },
      { label: 'When it hurts', text: 'Latch pain beyond the first 10 seconds, cracked nipples, or shooting pain after feeding aren\'t normal — call a lactation consultant, don\'t suffer through.' },
      { label: 'Combo feeding works', text: 'Breast, bottle, formula, or any combination — fed is the goal. Your mental health and ability to function matter as much as the source of the milk.' },
    ],
    suggestions: [
      'How do I prepare for breastfeeding before birth?',
      'What breast pump should I get?',
      'What is colostrum and when does it come?',
      'How do I know if breastfeeding is going well?',
    ],
  },
  {
    id: 'baby-gear',
    name: 'Baby Gear',
    icon: '🍼',
    description: 'Essential items, nursery setup, and what you actually need vs. marketing hype.',
    color: '#FDBA74',
    intro: 'The baby industry will try to sell you everything under the sun, love, but newborns truly need very little. Focus on safety essentials and resist the registry-creep until you know your baby\'s personality.',
    tips: [
      { label: 'Essentials only', text: 'A safe sleep space, car seat, diapers, 8-10 onesies, swaddles, and a few burp cloths. Skip wipe warmers, shoes, and most "smart" gadgets.' },
      { label: 'Safety first', text: 'Bare crib only — no pillows, bumpers, blankets, or toys until age 1. Car seat installed and inspected (most fire stations do it free) before due date.' },
      { label: 'Second-hand', text: 'Clothes, books, swings, and most furniture are great second-hand. Car seats and crib mattresses should be new or from a fully trusted source with no recall history.' },
      { label: 'Car seat install', text: 'Three out of four car seats are installed wrong. Use the LATCH system OR the seat belt, never both, and the seat shouldn\'t move more than an inch.' },
      { label: 'Diapers strategy', text: 'Don\'t stockpile newborn size — many babies skip it. Buy one pack of newborn, one of size 1, and assess from there. Babies use 8-12 diapers a day.' },
      { label: 'Bassinet vs crib', text: 'A bassinet next to your bed for the first 6 months is recommended by the AAP for safe sleep and easier night feeds. Then transition to a crib.' },
      { label: 'Stroller test', text: 'Test fold and unfold one-handed before buying — you\'ll do this hundreds of times. A travel system (car seat clicks into stroller) saves headache early on.' },
      { label: 'Wait to buy', text: 'Hold off on bottles, pacifiers, and carriers until baby arrives — preferences are personal. Buy one of each style and stock up on what works.' },
      { label: 'Registry rule', text: 'Add a range of price points so everyone can contribute. Diapers, wipes, and gift cards make the most genuinely useful gifts.' },
    ],
    suggestions: [
      'What baby gear do I actually need?',
      'How do I set up a safe nursery?',
      'What car seat is best for a newborn?',
      'What can I buy second-hand safely?',
    ],
  },
  {
    id: 'partner-support',
    name: 'Partner Support',
    icon: '💑',
    description: 'How partners can actively support during pregnancy, labor, and postpartum.',
    color: '#86EFAC',
    intro: 'Pregnancy is a team sport, dear, and the partner role matters far more than people realize. Showing up consistently — at appointments, at 3am, in the small daily moments — sets the tone for the whole family.',
    tips: [
      { label: 'Be present', text: 'Attend appointments, ask questions, and show interest in baby\'s development. Hearing the heartbeat together at week 10-12 changes everything.' },
      { label: 'Practical help', text: 'Take on more household tasks, cook meals, and handle nursery setup. Cleaning litter boxes (toxoplasmosis risk) becomes the partner\'s job — non-negotiable.' },
      { label: 'Birth support', text: 'Learn the labor stages, practice breathing techniques together, and know the birth plan well enough to advocate for it when she can\'t.' },
      { label: 'Emotional anchor', text: 'Hormones can swing fast and hard. Listen without trying to fix, validate the feelings, and don\'t take mood shifts personally — they\'re biology.' },
      { label: 'Comfort kit', text: 'During labor: ice chips, lip balm, a playlist, a hair tie, and counter-pressure on the lower back during contractions. Be the comfort manager.' },
      { label: 'Protect rest', text: 'Postpartum, take night shifts with pumped milk or formula so she gets one 4-5 hour sleep block. Sleep deprivation is the hardest part of the fourth trimester.' },
      { label: 'Gatekeep visitors', text: 'Postpartum visitors should bring food, not expectations. Be the one who says "come for 30 minutes, hold the baby while she showers, then go."' },
      { label: 'Watch for PPD', text: 'Up to 1 in 7 moms develop postpartum depression, and partners often spot it first. Sudden withdrawal, rage, hopelessness, or scary thoughts mean call the OB today.' },
      { label: 'Your feelings count', text: 'Up to 10% of dads/partners experience postpartum depression too. Talk to someone, exercise, and don\'t bottle it up — your wellness keeps the family afloat.' },
    ],
    suggestions: [
      'How can my partner support me during pregnancy?',
      'What role does the partner play during labor?',
      'How do we prepare as a team for the baby?',
      'What should partners know about postpartum?',
    ],
  },
  {
    id: 'postpartum-prep',
    name: 'Postpartum Prep',
    icon: '🌙',
    description: 'What to expect after birth — recovery, emotions, and the fourth trimester.',
    color: '#FDE68A',
    intro: 'The fourth trimester — those first 12 weeks after birth — is when YOU need the most care, sweetheart. Preparing for postpartum before baby comes is the kindest gift you can give your future self.',
    tips: [
      { label: 'Recovery takes time', text: 'Your body needs 6-8 weeks minimum to recover, longer for c-sections. Accept help, rest when baby sleeps, and be gentle with yourself about everything.' },
      { label: 'Baby blues vs PPD', text: 'Feeling weepy and emotional in the first 2 weeks is normal hormone crash. If sadness, anxiety, rage, or numbness persist past 2 weeks, call your OB the same day.' },
      { label: 'Meal prep now', text: 'Freeze 10-15 meals before birth. You won\'t want to cook with a newborn. Accept every meal offer, and set up a meal train through Take Them A Meal or similar.' },
      { label: 'Postpartum supplies', text: 'Stock up on adult diapers, peri bottle, witch hazel pads, dermoplast spray, stool softener, and large overnight pads. The hospital sends you home with starters — buy more.' },
      { label: 'Bleeding timeline', text: 'Lochia (postpartum bleeding) lasts 4-6 weeks, going from red to pink to yellow. Saturating a pad in under an hour or passing golf-ball clots means call the doctor.' },
      { label: 'Pelvic floor', text: 'See a pelvic floor physical therapist around week 6, regardless of delivery type. Standard in Europe, life-changing in the US — leaks and pain aren\'t something you have to live with.' },
      { label: 'Visitor boundaries', text: 'You don\'t owe anyone a visit. Set rules in advance: wash hands, no kissing baby, no visits if sick, no unsolicited advice. Partner enforces.' },
      { label: 'Hormone whiplash', text: 'Days 3-5 estrogen drops faster than at any other point in life. Crying randomly, night sweats, hair shedding around month 3 — all normal physiology.' },
      { label: 'Identity shift', text: 'Matrescence is the developmental transition into motherhood, like adolescence. Feeling like a stranger to yourself for months is normal, not a red flag.' },
    ],
    suggestions: [
      'How long does postpartum recovery take?',
      'What\'s the difference between baby blues and postpartum depression?',
      'How do I prepare for the first weeks at home?',
      'What postpartum supplies should I buy now?',
    ],
  },
  {
    id: 'pregnancy-nutrition',
    name: 'Nutrition',
    icon: '🥗',
    description: 'What to eat, what to avoid, and supplements for each trimester.',
    color: '#86EFAC',
    intro: 'You\'re not eating for two, dear — you\'re eating twice as well for one. Quality matters far more than quantity, and the actual extra calorie need is only about 340/day in the second trimester and 450 in the third.',
    tips: [
      { label: 'Folic acid', text: 'Take 400-800mcg daily from before conception through the first trimester. Critical for neural tube development, which closes by week 6.' },
      { label: 'What to avoid', text: 'Raw fish, unpasteurized cheese, deli meats (unless heated), high-mercury fish (shark, swordfish, king mackerel), alcohol, and excess caffeine (limit 200mg/day).' },
      { label: 'Iron-rich foods', text: 'Your blood volume increases 50%. Eat red meat, spinach, lentils, and fortified cereals — pair with vitamin C (orange, peppers) for better absorption.' },
      { label: 'Prenatal vitamin', text: 'Take it daily even if your diet is perfect — folate, iron, iodine, choline, and DHA in one pill. Take with food and at night if it triggers nausea.' },
      { label: 'Protein target', text: 'Aim for about 75-100g of protein daily — roughly your weight in pounds divided by 2. Eggs, Greek yogurt, beans, fish, and lean meats are workhorses.' },
      { label: 'Hydration', text: 'Drink 8-12 cups of water a day, more if you exercise or it\'s hot. Pale yellow urine is the goal. Dehydration triggers Braxton Hicks contractions.' },
      { label: 'Safe seafood', text: 'Salmon, sardines, trout, and shrimp are low-mercury and high in omega-3s. Aim for 8-12 oz per week — DHA is critical for baby\'s brain.' },
      { label: 'Sushi truth', text: 'Cooked rolls and veggie rolls are fine. Avoid raw fish in the US (listeria risk), but in countries with strict sushi standards, well-sourced raw fish is debated.' },
      { label: 'Cravings honest', text: 'Cravings rarely signal a real deficiency, but they\'re not the enemy. The 80/20 rule — nourishing meals 80% of the time, what you crave the other 20% — works.' },
    ],
    suggestions: [
      'What foods should I avoid during pregnancy?',
      'What supplements do I need this trimester?',
      'How much water should I drink while pregnant?',
      'Can I eat sushi during pregnancy?',
    ],
  },
  {
    id: 'emotional-wellness',
    name: 'Emotional Wellness',
    icon: '🧘',
    description: 'Managing anxiety, mood swings, and building emotional resilience.',
    color: '#67E8F9',
    intro: 'Growing a human is emotional work, love — your hormones are doing somersaults and your identity is shifting underneath you. Tending your mind is just as important as tending your body, and asking for help is strength, not weakness.',
    tips: [
      { label: 'Mood swings normal', text: 'Estrogen and progesterone rise dramatically in pregnancy. Crying at commercials, sudden irritability, and emotional whiplash are biology, not personality.' },
      { label: 'Anxiety check', text: 'Some worry about baby\'s health is normal. If anxiety is consuming your thoughts, affecting sleep, or causing panic attacks, ask your OB about therapy — many therapists specialize in perinatal mental health.' },
      { label: 'Self-care basics', text: 'Prenatal yoga, daily walks, warm (not hot) baths, journaling, and connecting with other expecting parents. Twenty minutes of nature lowers cortisol measurably.' },
      { label: 'Prenatal depression', text: 'About 1 in 7 women experience depression DURING pregnancy, not just after. Persistent sadness, loss of interest, or hopelessness deserves the same urgent care as PPD.' },
      { label: 'Limit doom scrolling', text: 'Pregnancy forums and Google can fuel anxiety fast. Set a time limit, choose 1-2 trusted sources, and ask your OB about your specific worries instead.' },
      { label: 'Birth fears (tokophobia)', text: 'Intense fear of childbirth affects 6-10% of pregnant women. Hypnobirthing classes, therapy, and an in-depth talk with your provider about pain options all help.' },
      { label: 'Relationships shift', text: 'Friendships with non-parents may change, partner dynamics will renegotiate. Talk openly, set realistic expectations, and consider a couples session before baby arrives.' },
      { label: 'Sleep is mental health', text: 'Sleep deprivation amplifies every emotion. Prioritize naps, side-sleeping setup, and partner-led night routines — protecting sleep protects mood.' },
      { label: 'When to escalate', text: 'Thoughts of harming yourself or baby, inability to function, or feeling completely disconnected from the pregnancy are emergencies. Call your OB or 988 today, not tomorrow.' },
    ],
    suggestions: [
      'Is it normal to feel anxious during pregnancy?',
      'How can I manage pregnancy mood swings?',
      'What relaxation techniques are safe during pregnancy?',
      'When should I seek help for prenatal anxiety?',
    ],
  },
]
