import type { Pillar } from '../types'

export const prePregPillars: Pillar[] = [
  {
    id: 'fertility',
    name: 'Fertility Basics',
    icon: '🌸',
    description: 'Cycle tracking, ovulation, conception tips, and understanding your fertile window.',
    color: '#F9A8D4',
    intro: 'Your body has a rhythm, dear, and learning it is the single most powerful thing you can do this season. Fertility is not a coin flip — it is a six-day window each month, and most people who understand that window conceive within six cycles.',
    tips: [
      { label: 'Know your cycle', text: 'Track your period to identify your fertile window — typically days 10-16 of a 28-day cycle. Ovulation is when conception can happen.' },
      { label: 'Ovulation signs', text: 'Watch for egg-white cervical mucus, mild pelvic cramps, and a slight temperature rise of 0.3-0.5°C. These signal ovulation is happening or just happened.', phases: ['ovulation'] },
      { label: 'Timing matters', text: 'The best chance of conception is the 2 days before ovulation, not the day of. Sperm can survive up to 5 days inside the body, but the egg only lives 12-24 hours.', phases: ['follicular', 'ovulation'] },
      { label: 'Frequency over precision', text: 'Having sex every 1-2 days through your fertile window beats trying to pinpoint the exact ovulation day. Daily is fine — sperm count rebounds quickly.', phases: ['follicular', 'ovulation'] },
      { label: 'LH strips help', text: 'Ovulation predictor kits detect the LH surge 24-36 hours before ovulation. Test in the early afternoon, not first morning urine, for the most accurate read.', phases: ['follicular', 'ovulation'] },
      { label: 'BBT confirms, not predicts', text: 'Basal body temperature charting tells you ovulation already happened — useful for learning your pattern over 2-3 cycles, but not for catching it in real time.', phases: ['ovulation', 'luteal'] },
      { label: 'Skip the douching and lube', text: 'Most lubricants are sperm-toxic. If you need one, use a fertility-friendly brand like Pre-Seed. Skip douching entirely — it disrupts vaginal pH.' },
      { label: 'Give it time', text: 'In healthy couples under 35, about 85% conceive within a year of trying. It is not a race, and a normal cycle or two without success is not a problem.' },
      { label: 'When to see a doctor', text: 'See a fertility specialist after 12 months of trying if you are under 35, after 6 months if you are 35-39, and right away if you are 40 or have irregular cycles.' },
    ],
    suggestions: [
      'How do I track my ovulation?',
      'What is the best time to conceive?',
      'How long does it typically take to get pregnant?',
      'What are signs that I\'m ovulating?',
    ],
  },
  {
    id: 'nutrition-prep',
    name: 'Nutrition Prep',
    icon: '🥑',
    description: 'Prenatal vitamins, folic acid, diet optimization, and preparing your body.',
    color: '#86EFAC',
    intro: 'Think of the months before conception as setting the table, love — the eggs maturing right now were recruited about 90 days ago, so what you eat today builds the cells that may become your baby. You do not need to overhaul everything, just a few non-negotiables and a Mediterranean-leaning plate.',
    tips: [
      { label: 'Start folic acid now', text: 'Take 400mcg of folic acid daily at least 1-3 months before conceiving. It prevents neural tube defects that form in the first 28 days, often before you know you are pregnant.' },
      { label: 'Prenatal vitamins early', text: 'Start a prenatal vitamin with folic acid, iron, iodine, choline, and DHA before conception — not after. Look for methylfolate if you carry an MTHFR variant.' },
      { label: 'Clean up your diet', text: 'Reduce processed foods, increase fruits, vegetables, whole grains, and lean proteins. Limit caffeine to 200mg/day — about one 12oz coffee.' },
      { label: 'Mediterranean wins', text: 'Studies consistently link a Mediterranean diet — olive oil, fish, legumes, nuts, vegetables — to better fertility outcomes in both partners. It is the most evidence-backed pattern.' },
      { label: 'Mind your weight', text: 'A BMI between 20 and 25 is associated with the easiest conception. Being significantly underweight or overweight can disrupt ovulation, but small, sustainable changes matter more than crash dieting.' },
      { label: 'Watch the mercury', text: 'Skip swordfish, king mackerel, tilefish, and bigeye tuna now — mercury builds up over months. Salmon, sardines, and shrimp are excellent low-mercury choices.' },
      { label: 'Iron and ferritin', text: 'Low iron stores are common and linked to anovulation. Ask for a ferritin check, aim above 30 ng/mL, and pair iron-rich foods with vitamin C for absorption.', phases: ['menstruation'] },
      { label: 'Hydrate properly', text: 'Cervical mucus is mostly water — aim for 2-2.5 liters daily. Dehydration shows up first as scant or sticky mucus, which makes the fertile window harder to read.', phases: ['ovulation'] },
      { label: 'Cut the alcohol', text: 'There is no proven safe amount of alcohol during the trying-to-conceive window. Even moderate drinking is linked to lower fertility — save the wine for special meals or skip it.' },
      { label: 'Avoid raw and unpasteurized', text: 'Get used to skipping raw fish, undercooked meat, unpasteurized cheese, and deli meats now. Building the habit before pregnancy is easier than during the first-trimester nausea.' },
    ],
    suggestions: [
      'When should I start taking prenatal vitamins?',
      'What foods boost fertility?',
      'Should I change my diet before trying to conceive?',
      'How much folic acid do I need?',
    ],
  },
  {
    id: 'emotional-readiness',
    name: 'Emotional Readiness',
    icon: '💛',
    description: 'Managing expectations, anxiety, and preparing emotionally for parenthood.',
    color: '#FDE68A',
    intro: 'The two-week wait can feel longer than the two-week vacation you actually deserve, dear. Emotional readiness is not about feeling certain — it is about building the resilience to ride the waves of hope, disappointment, and the slow shift into becoming a parent.',
    tips: [
      { label: 'It\'s a journey', text: 'Getting pregnant can take time. The average healthy couple takes 6-12 months. Be patient with yourself and your body.' },
      { label: 'Talk about it', text: 'Discuss fears, expectations, and parenting values with your partner. Alignment now prevents conflict later — especially around discipline, faith, and division of labor.' },
      { label: 'Manage stress', text: 'High chronic stress can affect ovulation timing. Practice meditation, exercise, and set firm boundaries around the trying-to-conceive process — including who you tell.' },
      { label: 'Protect your scroll', text: 'Mute or unfollow accounts that trigger comparison or panic during the two-week wait. TTC forums can be supportive or corrosive — choose your inputs deliberately.', phases: ['luteal'] },
      { label: 'Name the grief', text: 'A negative test, an early loss, or a friend\'s pregnancy announcement can hit hard. These feelings are real grief, not overreaction, and they deserve space, not suppression.', phases: ['menstruation'] },
      { label: 'Therapy is not a last resort', text: 'A therapist who specializes in perinatal or fertility issues can be invaluable, especially after 6 months of trying. It is preventive care, not a sign something is wrong.' },
      { label: 'Keep a life outside TTC', text: 'Schedule things that have nothing to do with conceiving — a trip, a class, a project. Identity that depends entirely on becoming pregnant gets fragile fast.' },
      { label: 'Sleep is fertility', text: 'Aim for 7-9 hours. Poor sleep disrupts cortisol and reproductive hormones, and a tired version of you is a more anxious version of you.' },
      { label: 'Decide who to tell', text: 'You do not owe anyone an update. Picking one or two safe people — and a clear answer for nosy relatives — protects your energy through the unknowns.' },
    ],
    suggestions: [
      'How do I deal with the stress of trying to conceive?',
      'Is it normal to feel anxious about getting pregnant?',
      'How do I stay positive during the TTC journey?',
      'What conversations should we have before trying?',
    ],
  },
  {
    id: 'financial-planning',
    name: 'Financial Planning',
    icon: '💰',
    description: 'Budgeting for baby, insurance coverage, and planning ahead financially.',
    color: '#FDBA74',
    intro: 'Money is one of those topics, love, that feels unromantic next to the idea of a baby — and yet it is one of the kindest gifts you can give your future family. A little planning now buys you calm later, when the only thing you want to think about is the little face in your arms.',
    tips: [
      { label: 'Insurance review', text: 'Check your health insurance for maternity coverage, deductibles, in-network hospitals, and pediatrician networks before conceiving. Some plans have waiting periods or exclude fertility care.' },
      { label: 'Baby budget', text: 'The first year costs $12,000-$15,000 on average in the US. Start saving now for diapers, formula or feeding supplies, childcare, gear, and a pediatrician copay schedule.' },
      { label: 'Emergency fund', text: 'Aim for 3-6 months of expenses saved before conceiving. Pregnancy can bring unexpected costs, bed rest, or a partner needing time off work.' },
      { label: 'Know your parental leave', text: 'Read your employer\'s leave policy and your country or state\'s statutory leave before you tell anyone you are trying. Knowing your paid versus unpaid weeks shapes every other decision.' },
      { label: 'Run the childcare math', text: 'Daycare or a nanny can rival rent or mortgage payments. Get current quotes in your area now — the answer often shifts who returns to work, and when.' },
      { label: 'Update beneficiaries and wills', text: 'Add or update life insurance, retirement beneficiaries, and a basic will with guardianship language. These are awkward to think about and far more awkward to leave undone.' },
      { label: 'Tax-advantaged accounts', text: 'A health FSA or HSA can cover prenatal and birth costs with pre-tax dollars. Dependent care FSAs help with childcare later — confirm enrollment windows now.' },
      { label: 'Build the buffer, not the nursery', text: 'A stocked savings account beats a Pinterest-perfect nursery. Babies need very little gear in the first three months — secondhand is fine for most of it.' },
      { label: 'Talk numbers together', text: 'Share full visibility of income, debt, and spending with your partner before trying. Financial surprises after a baby arrives are one of the top sources of new-parent conflict.' },
    ],
    suggestions: [
      'How much does having a baby cost?',
      'What should I budget for in the first year?',
      'How do I check my maternity insurance coverage?',
      'When should I start a college savings fund?',
    ],
  },
  {
    id: 'partner-journey',
    name: 'Partner Journey',
    icon: '💑',
    description: 'Preparing together, shared health checks, and building a strong foundation.',
    color: '#C4B5FD',
    intro: 'Conception takes two, dear, and so does everything that comes after. The months before trying are a rare window to align as teammates — your bodies, your habits, and the quiet expectations you each carry about what parenthood will look like.',
    tips: [
      { label: 'Both get checked', text: 'Both partners should have a pre-conception checkup. Male factors account for about 40-50% of conception difficulties — semen analysis is quick, cheap, and informative.' },
      { label: 'Lifestyle together', text: 'Both partners should quit smoking, limit alcohol, and improve diet. Sperm takes about 74 days to mature, so changes today show up in 2-3 months.' },
      { label: 'Communication', text: 'Discuss parenting styles, division of responsibilities, faith and discipline values, and support systems before pregnancy begins. Write down the agreements you reach.' },
      { label: 'Mind the heat', text: 'Have your partner skip hot tubs, saunas, and laptop-on-lap habits. Sperm production needs testes about 2°C cooler than core body temp — heat lowers count and motility.', phases: ['follicular', 'ovulation'] },
      { label: 'Sperm-friendly habits', text: 'Encourage daily exercise, weight in a healthy range, zinc and antioxidant-rich foods, and an end to tight cycling shorts and recreational drug use. Marijuana lowers sperm count.' },
      { label: 'Share the tracking load', text: 'Fertility tracking apps and ovulation tests work better with two engaged people. Let your partner own a piece — checking strips, logging temps — so it does not all live on you.', phases: ['follicular', 'ovulation'] },
      { label: 'Sex without scoreboard', text: 'Scheduled fertile-window sex can drain intimacy fast. Keep non-conception sex in the rotation, and protect a few date nights that have nothing to do with making a baby.', phases: ['follicular', 'ovulation'] },
      { label: 'Practice the hard talks', text: 'Discuss what you would do with a difficult prenatal diagnosis, a long fertility journey, or a NICU stay. These conversations are easier in the calm before, not the storm.' },
      { label: 'Build your village together', text: 'Identify the friends, family, and professionals you both trust. A baby is far easier in a network of three to five reliable adults than just two exhausted ones.' },
    ],
    suggestions: [
      'Should my partner also see a doctor before trying?',
      'How can my partner improve fertility?',
      'What lifestyle changes should we make together?',
      'How do we prepare our relationship for a baby?',
    ],
  },
  {
    id: 'health-checkups',
    name: 'Health Checkups',
    icon: '🩺',
    description: 'Pre-conception tests, genetic screening, and getting your body ready.',
    color: '#93C5FD',
    intro: 'A pre-conception visit is the most underrated appointment in medicine, love. One hour with your doctor 3-6 months before trying can catch the small things — an under-treated thyroid, a missing vaccine, a medication that needs swapping — that quietly shape how easily a pregnancy begins.',
    tips: [
      { label: 'Pre-conception visit', text: 'See your OB/GYN 3-6 months before trying. Discuss medications, chronic conditions, family history, and vaccination status (rubella, varicella, Tdap, COVID, flu).' },
      { label: 'Genetic screening', text: 'Expanded carrier screening can identify if you or your partner carry genes for cystic fibrosis, sickle cell, spinal muscular atrophy, and 200+ conditions. Done once per lifetime.' },
      { label: 'Dental check', text: 'Get cleanings, x-rays, and any restorative work done before pregnancy. Pregnancy hormones worsen gum disease, and some procedures and medications are restricted later.' },
      { label: 'Thyroid panel', text: 'Ask for TSH and free T4. An underactive thyroid is common, often silent, and linked to miscarriage and developmental issues — easy to treat once identified.' },
      { label: 'Review every medication', text: 'Bring a list of every prescription, OTC, and supplement to your doctor. Some acne meds (isotretinoin), blood pressure drugs (ACE inhibitors), and mood meds need swapping before conception.' },
      { label: 'Update vaccines early', text: 'Live vaccines like MMR and varicella must be given at least one month before conceiving. Get Tdap, flu, and COVID boosters up to date too.' },
      { label: 'Screen for STIs', text: 'Chlamydia, gonorrhea, and untreated syphilis can damage fallopian tubes and harm a future baby. A quick screen for both partners is standard pre-conception care.' },
      { label: 'Manage chronic conditions', text: 'Diabetes, hypertension, autoimmune disease, and epilepsy all benefit from being well-controlled before conception — not after a positive test. Loop in your specialist now.' },
      { label: 'Vitamin D and B12', text: 'Ask for vitamin D and B12 levels, especially if you eat plant-based or live somewhere with long winters. Both deficiencies are common and affect fertility and early pregnancy.' },
      { label: 'Know your family history', text: 'Ask both sides about miscarriages, birth defects, blood clots, and inherited conditions. Bring that map to your pre-conception visit — it changes which tests are worth running.' },
    ],
    suggestions: [
      'What tests should I get before trying to conceive?',
      'Should we do genetic testing?',
      'What medications should I stop before pregnancy?',
      'Do I need any vaccinations before getting pregnant?',
    ],
  },
]
