/**
 * weekContent — per-week development, symptoms, and prep data.
 * Ported 1:1 from `weekContent` in pregnancy-weeks.html.
 */

import type { StickerIconName } from '../components/home/pregnancy/stickerIcons'

export interface PrepItemDef {
  i: StickerIconName
  t: string
  d: string
}

export interface WeekContent {
  trim: 'First' | 'Second' | 'Third' | 'Overdue'
  dev: string[]
  sym: string[]
  prep: PrepItemDef[]
}

export const weekContent: Record<number, WeekContent> = {
  1: { trim: 'First', dev: ['Your body sheds its uterine lining — a fresh cycle begins', 'Hormones are quietly preparing your ovaries for ovulation', "Conception hasn't happened yet — pregnancy is dated from your last period"], sym: ['Period cramps', 'Lower back pain', 'Fatigue', 'Mood shifts'], prep: [{ i: 'leaf', t: 'Start prenatal vitamins', d: 'Folate before conception protects the neural tube' }, { i: 'leaf', t: 'Eat iron-rich foods', d: 'Replenish stores lost during your period' }, { i: 'calendar', t: 'Track your cycle', d: 'Knowing ovulation day boosts conception odds' }] },
  2: { trim: 'First', dev: ['An egg is maturing inside a follicle', 'The uterine lining thickens in preparation', 'Fertile window approaching — ovulation is days away'], sym: ['Clear stretchy cervical mucus', 'Slight pelvic twinge', 'Higher libido', 'Heightened sense of smell'], prep: [{ i: 'calendar', t: 'Track basal body temperature', d: 'A rise signals ovulation has happened' }, { i: 'heart', t: 'Plan intimacy', d: 'Days 11–14 of your cycle are peak fertile' }, { i: 'yoga', t: 'Reduce stress', d: 'Cortisol can interfere with ovulation' }] },
  3: { trim: 'First', dev: ['Sperm meets egg — a unique genetic code is formed', 'The zygote starts dividing as it travels down the fallopian tube', 'Baby is a tiny cluster of cells called a morula'], sym: ['Implantation spotting (possible)', 'Mild cramps', 'Breast tenderness', 'Bloating'], prep: [{ i: 'pill', t: 'Keep taking folate', d: 'Critical time for neural tube formation' }, { i: 'nosmoke', t: 'Stop alcohol + smoking', d: 'Eliminate any exposure now' }, { i: 'mug', t: 'Limit caffeine', d: 'Aim for under 200mg/day' }] },
  4: { trim: 'First', dev: ['The blastocyst implants in the uterine wall', 'The placenta begins forming', 'hCG starts rising — tests may soon read positive'], sym: ['Missed period', 'Breast tenderness', 'Mild spotting', 'Early fatigue', 'Slight nausea'], prep: [{ i: 'test', t: 'Take a pregnancy test', d: 'hCG should be detectable in urine now' }, { i: 'phone', t: 'Book first OB appointment', d: 'Usually scheduled around week 8' }, { i: 'couch', t: 'Rest when tired', d: 'Your body is working hard — listen to it' }] },
  5: { trim: 'First', dev: ['The neural tube closes — basis for brain and spinal cord', 'A tiny heart starts pulsing', 'Arm and leg buds begin appearing'], sym: ['Morning sickness starts', 'Extreme fatigue', 'Frequent urination', 'Food aversions', 'Emotional waves'], prep: [{ i: 'bottle', t: 'Eat small frequent meals', d: 'Helps keep nausea at bay' }, { i: 'drop', t: 'Stay hydrated', d: 'Water, ginger tea, broth — sip often' }, { i: 'nosmoke', t: 'Avoid secondhand smoke', d: 'Critical time for organ formation' }] },
  6: { trim: 'First', dev: ['Heart beats around 110 bpm and may be visible on ultrasound', 'Facial features start forming', 'Brain divides into sections'], sym: ['Morning sickness peaks', 'Bloating', 'Mood swings', 'Breast changes', 'Metallic taste'], prep: [{ i: 'stethoscope', t: 'Schedule first ultrasound', d: 'Confirms pregnancy and detects heartbeat' }, { i: 'apple', t: 'Try bland carbs', d: 'Crackers, toast, rice help with nausea' }, { i: 'moon', t: 'Prioritize sleep', d: '8–10 hours helps with hormone shifts' }] },
  7: { trim: 'First', dev: ['Arms and legs lengthen with visible joints', 'Eyes, nostrils and ears are forming', 'Liver starts producing red blood cells'], sym: ['Continued nausea', 'Fatigue', 'Cravings & aversions', 'Acne', 'Frequent urination'], prep: [{ i: 'family', t: 'Decide who to tell', d: 'Some wait for week 12 — your call' }, { i: 'book', t: 'Read trimester guide', d: 'Know what to expect week-by-week' }, { i: 'leaf', t: 'Eat protein regularly', d: 'Supports rapid cell division' }] },
  8: { trim: 'First', dev: ['All essential organs are present in basic form', 'Fingers and toes begin separating', 'Baby officially transitions from embryo to fetus'], sym: ['Possibly showing slightly', 'Heightened sense of smell', 'Constipation', 'Heartburn starts', 'Dizziness'], prep: [{ i: 'home', t: 'First prenatal visit', d: 'Blood work, urine, health history' }, { i: 'plate', t: 'Focus on nutrition quality', d: '~150 extra calories is all you need' }, { i: 'yoga', t: 'Try prenatal yoga', d: 'Gentle movement eases symptoms' }] },
  9: { trim: 'First', dev: ['Tiny embryonic tail is completely gone', 'Essential organs exist and begin functioning', 'Baby can make small spontaneous movements'], sym: ['Morning sickness continues', 'Visible veins', 'Vivid dreams', 'Bloating', 'Mood swings'], prep: [{ i: 'scan', t: 'Consider early dating scan', d: 'Accurately dates pregnancy + checks heartbeat' }, { i: 'music', t: 'Start mindfulness', d: 'Apps help with pregnancy anxiety' }, { i: 'bulb', t: 'Research birth options', d: 'Hospital, birth center, or home birth' }] },
  10: { trim: 'First', dev: ['External genitalia are starting to form', 'Kidneys are producing urine', 'Fingernails begin growing'], sym: ['Nausea may start easing', 'Visible weight gain', 'Round ligament pain', 'Headaches'], prep: [{ i: 'test', t: 'Consider NIPT screening', d: 'Noninvasive genetic test available after week 10' }, { i: 'calendar', t: 'Track weight gain', d: 'Expect 1–5 lbs in first trimester' }, { i: 'wine', t: 'Eliminate alcohol', d: 'No safe amount during pregnancy' }] },
  11: { trim: 'First', dev: ['Diaphragm forms — baby may start "hiccup" movements', 'Fingers and toes fully separated', 'Bones begin hardening'], sym: ['Increased energy (sometimes)', 'Skin changes', 'Darkening areolas', 'Continued frequent urination'], prep: [{ i: 'test', t: 'First trimester screening', d: 'Blood test + nuchal translucency scan (wks 11–14)' }, { i: 'shoe', t: 'Shop for basic maternity', d: 'Stretchy waistbands become your friend' }, { i: 'tooth', t: 'Schedule dental cleaning', d: 'Hormones affect gums — oral health matters' }] },
  12: { trim: 'First', dev: ['Baby has working nervous system reflexes', 'Vocal cords are forming', 'Can curl fingers and toes'], sym: ['Miscarriage risk drops sharply', 'Uterus rising into abdomen', 'Less frequent urination', 'Nausea easing'], prep: [{ i: 'sparkle', t: 'Consider announcing', d: 'Miscarriage risk falls below 1% after week 12' }, { i: 'clipboard', t: 'Review screening results', d: 'Discuss findings with your provider' }, { i: 'dumbbell', t: 'Start pelvic floor exercises', d: 'Kegels protect you through birth and recovery' }] },
  13: { trim: 'First', dev: ['Vocal cords fully formed (no air to use them yet)', 'Unique fingerprints start forming', 'Placenta takes over hormone production'], sym: ['Energy starts returning', 'Nausea fading', 'Potential bump forming', 'Increased appetite'], prep: [{ i: 'flower', t: 'First trimester complete', d: "You're one-third of the way there!" }, { i: 'scan', t: 'Book 20-week anatomy scan', d: 'Most detailed scan — coming in weeks 18–22' }, { i: 'book', t: 'Start a pregnancy journal', d: 'Weeks ahead are full of milestones' }] },
  14: { trim: 'Second', dev: ["Baby's face becomes more expressive", 'Neck is longer, head more upright', 'Organs like liver, spleen, kidneys begin working'], sym: ['Energy boost (second trimester glow)', 'Breast tenderness fades', 'Growing appetite', 'Round ligament pain'], prep: [{ i: 'yoga', t: 'Start pregnancy fitness', d: 'Walking, swimming, prenatal yoga' }, { i: 'basket', t: 'Start registry research', d: 'No rush — just gather ideas' }, { i: 'apple', t: 'Increase healthy calories', d: '~300 extra per day in trimester 2' }] },
  15: { trim: 'Second', dev: ['Baby can sense light through your belly', 'Starts practicing breathing movements', 'Bones continue hardening'], sym: ['Stretch marks may appear', 'Linea nigra (dark line) forming', 'Round ligament pain', 'Nasal congestion'], prep: [{ i: 'drop', t: 'Moisturize belly + thighs', d: 'May reduce stretch mark severity' }, { i: 'test', t: 'Consider amniocentesis', d: 'If genetic concerns, discuss with provider' }, { i: 'shoe', t: 'Comfortable shoes', d: 'Feet swell as pregnancy progresses' }] },
  16: { trim: 'Second', dev: ['Baby can hear sounds — start talking and singing!', 'Tiny facial muscles allow frowning and squinting', 'May sense light through closed eyelids'], sym: ['First flutters (quickening) possible', 'Growing bump visible', 'Backache starts', 'Pregnancy glow'], prep: [{ i: 'music', t: 'Start reading/singing to baby', d: 'Baby can now hear your voice' }, { i: 'pencil', t: 'Quad screen test', d: 'Blood test for chromosomal conditions (15–20 wks)' }, { i: 'moon', t: 'Try left-side sleeping', d: 'Best blood flow for baby' }] },
  17: { trim: 'Second', dev: ['Fat layers start developing', 'Sweat glands begin forming', 'Baby can move all joints'], sym: ['Increased appetite', 'Feeling baby movements', 'Forgetfulness (pregnancy brain)', 'Heart races occasionally'], prep: [{ i: 'plate', t: 'Iron-rich meals', d: 'Blood volume increasing — prevent anemia' }, { i: 'book', t: 'Research childbirth classes', d: 'Book early — most start in 3rd trimester' }, { i: 'phone', t: 'Download a kick counter', d: "Useful for monitoring baby's patterns" }] },
  18: { trim: 'Second', dev: ['Ears in final position, baby hears clearly', 'Nervous system forming myelin', 'Yawning and hiccuping visible on ultrasound'], sym: ['Leg cramps', 'Backaches', 'Occasional dizziness', 'Varicose veins'], prep: [{ i: 'scan', t: 'Schedule anatomy scan', d: 'Between weeks 18–22 — a major milestone' }, { i: 'clipboard', t: 'Plan maternity leave', d: 'Talk to HR about policies and dates' }, { i: 'pill', t: 'Check iron levels', d: 'Supplement if low to prevent anemia' }] },
  19: { trim: 'Second', dev: ['Vernix (protective waxy coating) covers skin', 'Lanugo (fine hair) covers body', 'Brain developing rapidly — touch sensitivity'], sym: ['Pelvic pain', 'Round ligament pain', 'Skin darkening', 'Hip pain'], prep: [{ i: 'yoga', t: 'Stretch regularly', d: 'Eases muscle and ligament pain' }, { i: 'drop', t: 'Hydrate for headaches', d: 'Dehydration is a common trigger' }, { i: 'book', t: 'Start reading baby books', d: 'Great time to learn newborn care' }] },
  20: { trim: 'Second', dev: ['Halfway there! Baby is about 6.4 inches long', 'Can swallow more — digestive system maturing', 'May respond to sounds or light'], sym: ['Visible kicks and movements', 'Heartburn returns', 'Shortness of breath', 'Bigger bump'], prep: [{ i: 'sparkle', t: 'Halfway celebration!', d: '20 weeks down, 20 to go' }, { i: 'scan', t: 'Anatomy scan', d: 'Detailed organ check + optional sex reveal' }, { i: 'basket', t: 'Finalize registry', d: 'Baby shower planning can start' }] },
  21: { trim: 'Second', dev: ['Baby swallows amniotic fluid for digestion practice', 'Taste buds forming — flavors pass through', 'Can respond to your voice'], sym: ['Faster weight gain', 'Stretch marks', 'Swollen feet', 'Braxton Hicks may start'], prep: [{ i: 'plate', t: 'Eat diverse flavors', d: 'Baby develops taste preferences now' }, { i: 'shoe', t: 'Low-heeled shoes', d: 'Center of gravity is shifting' }, { i: 'drop', t: 'Apply belly oil nightly', d: 'Keep skin supple and itch-free' }] },
  22: { trim: 'Second', dev: ['Eyebrows and eyelashes visible', 'Lips defined, tiny tooth buds forming', 'Lungs practicing breathing motions'], sym: ['Visible kicks', 'Stretch marks intensify', 'Back pain', 'Snoring'], prep: [{ i: 'couch', t: 'Pregnancy pillow', d: 'Side-sleeping gets more comfortable' }, { i: 'handshake', t: 'Choose a pediatrician', d: 'Interview a few options' }, { i: 'scan', t: 'Book maternity photos', d: 'Peak bump photogenic weeks: 30–36' }] },
  23: { trim: 'Second', dev: ['Baby hears high-pitched sounds from outside', 'Starts developing lung surfactant', 'Skin is still translucent'], sym: ['Linea nigra more visible', 'Swollen ankles', 'Increased heart rate', 'Braxton Hicks'], prep: [{ i: 'walk', t: 'Daily walks', d: "Good for circulation + baby's development" }, { i: 'pencil', t: 'Start birth plan draft', d: 'Think about preferences for labor' }, { i: 'family', t: 'Prepare older siblings', d: 'Start conversations about the new baby' }] },
  24: { trim: 'Second', dev: ['Inner ear fully developed — baby hears your heartbeat and voice clearly', 'Eyes can detect light through closed lids', 'Taste buds continue developing on the tongue', 'Lungs developing ability to breathe air — a major milestone'], sym: ['Backaches', 'Swollen feet and ankles', 'Braxton Hicks contractions', 'Heartburn', 'Vivid dreams', 'Shortness of breath'], prep: [{ i: 'apple', t: 'Prepare for glucose screening', d: 'Tests for gestational diabetes around week 24–28' }, { i: 'leaf', t: 'Draft your birth plan', d: 'Outline preferences for labor and delivery' }, { i: 'heart', t: 'Tour the birth center', d: 'Know your way around before labor begins' }, { i: 'steak', t: 'Boost iron-rich foods', d: 'Supports you and prevents anemia' }] },
  25: { trim: 'Second', dev: ['Skin is less translucent, more pinkish', 'Baby gains fat for warmth regulation', 'Nostrils begin to open'], sym: ['Aching back/hips', 'Itchy stretching skin', 'Leaky breasts (colostrum)', 'Restless legs'], prep: [{ i: 'syringe', t: 'Ask about Tdap timing', d: 'Typically given at weeks 27–36' }, { i: 'book', t: 'Book childbirth class', d: 'Many start mid-third trimester' }, { i: 'moon', t: 'Upgrade pillow setup', d: 'Between knees + under belly helps' }] },
  26: { trim: 'Second', dev: ['Eyes start to open and blink', 'Brain wave activity similar to newborn', 'Baby may startle at loud sounds'], sym: ['Tingling hands (carpal tunnel)', 'Leg cramps at night', 'Clumsiness', 'Growing belly button'], prep: [{ i: 'gift', t: 'Baby shower planning', d: 'Usually hosted between weeks 28–32' }, { i: 'stethoscope', t: 'Check blood pressure', d: 'Watch for preeclampsia signs' }, { i: 'bag', t: 'Start hospital bag list', d: "Don't pack yet — just research essentials" }] },
  27: { trim: 'Second', dev: ['Sleep-wake cycles forming', 'Lungs mature enough to function with intensive care', 'Baby recognizes familiar voices'], sym: ['Leg cramps', 'Hemorrhoids possible', 'Trouble sleeping', 'Rising fatigue'], prep: [{ i: 'syringe', t: 'Get Tdap vaccine', d: 'Passes pertussis immunity to baby' }, { i: 'test', t: 'Rh antibody test', d: 'If Rh-negative, RhoGAM injection given' }, { i: 'book', t: 'Breastfeeding research', d: 'La Leche League, books, classes' }] },
  28: { trim: 'Third', dev: ['Third trimester begins!', 'Baby can open eyes and blink', 'Sees dim light through uterine wall', 'Brain adding billions of neurons'], sym: ['Fatigue returning', 'Leg cramps', 'Shortness of breath', 'Insomnia', 'Pelvic pressure'], prep: [{ i: 'calendar', t: 'Biweekly appointments start', d: 'Visits become more frequent now' }, { i: 'book', t: 'Start birth classes', d: '6–8 week courses typically' }, { i: 'syringe', t: 'RhoGAM if Rh-negative', d: 'Standard at 28 weeks' }, { i: 'bottle', t: 'Research breastfeeding supplies', d: 'Pump, bottles, nursing bras' }] },
  29: { trim: 'Third', dev: ["Baby's muscles and lungs continuing to mature", 'Head growing for developing brain', 'Bones hardening — calcium demand high'], sym: ['More movement felt', 'Heartburn', 'Hemorrhoids', 'Dry itchy skin', 'Frequent urination'], prep: [{ i: 'bottle', t: 'Boost calcium intake', d: 'Baby taking 200mg/day from you' }, { i: 'tooth', t: 'Dental checkup', d: 'Pregnancy gingivitis common' }, { i: 'home', t: 'Pre-register at hospital', d: 'Saves time during labor' }] },
  30: { trim: 'Third', dev: ['Baby can turn head side to side', 'Eyelashes have grown in', 'Brain surface becoming wrinkled for more surface area'], sym: ['Increased back pain', 'Tingling/numbness in extremities', 'Round ligament pain', 'Swelling'], prep: [{ i: 'briefcase', t: 'Plan maternity leave start', d: 'Most start weeks 37–40 or at birth' }, { i: 'home', t: 'Start nesting projects', d: 'Nursery setup, decluttering' }, { i: 'basket', t: 'Big purchases (car seat, crib)', d: 'Have essentials by week 36' }] },
  31: { trim: 'Third', dev: ['Baby can process information and tracks light', 'All five senses working', 'Rapid brain development'], sym: ['Trouble sleeping', 'Rib pain', 'Leaky breasts', 'Braxton Hicks more frequent'], prep: [{ i: 'basket', t: 'Wash baby clothes + linens', d: 'Use fragrance-free detergent' }, { i: 'car', t: 'Install car seat', d: 'Get a professional check at fire station' }, { i: 'family', t: 'Plan for older children', d: 'Who will watch them during labor?' }] },
  32: { trim: 'Third', dev: ['Baby practicing breathing', 'Toenails visible', 'Most babies settle head-down now'], sym: ['Heartburn', 'Shortness of breath', 'Fatigue', 'Back pain', 'Trouble sleeping'], prep: [{ i: 'bag', t: 'Pack hospital bag', d: 'For you, partner, and baby' }, { i: 'pencil', t: 'Finalize birth plan', d: 'Share with your birth team' }, { i: 'bottle', t: 'Breast pump through insurance', d: 'Most plans cover one — order now' }] },
  33: { trim: 'Third', dev: ['Skull bones stay soft for birth', 'Immune system receiving antibodies from you', 'Can distinguish night from day'], sym: ['Peak heartburn', 'Water retention', 'Mild swelling', 'Decreased movement space'], prep: [{ i: 'teddy', t: 'Set up nursery', d: "Baby's sleeping space ready" }, { i: 'home', t: 'Hospital tour', d: 'Know the admission route' }, { i: 'clipboard', t: 'Plan baby insurance', d: 'Add to policy within 30 days of birth' }] },
  34: { trim: 'Third', dev: ['Central nervous system still maturing', 'Lungs nearly ready', 'Baby would have excellent chances if born now'], sym: ['Braxton Hicks stronger', 'Pelvic pressure', 'Fatigue', 'Swelling'], prep: [{ i: 'phone', t: 'Program emergency numbers', d: 'OB, hospital, partner, backup drivers' }, { i: 'map', t: 'Practice drive to hospital', d: 'At different times of day' }, { i: 'moon', t: 'Prep postpartum recovery area', d: 'Snacks, water, pads, pack-n-play' }] },
  35: { trim: 'Third', dev: ['Baby gaining about 1 ounce per day', 'Kidneys fully developed', 'Liver processing some waste'], sym: ['Lightening (baby dropping)', 'Pelvic pressure', 'Frequent urination', 'Walking waddle', 'Insomnia'], prep: [{ i: 'microbe', t: 'Group B Strep test', d: 'Swab between weeks 35–37' }, { i: 'baby', t: 'Practice newborn care', d: 'Diapering, swaddling tutorials' }, { i: 'bag', t: 'Put hospital bag in car', d: 'Be ready for any moment' }] },
  36: { trim: 'Third', dev: ['Baby is officially "full-term eligible"', 'Most vernix and lanugo gone', 'Gaining half pound per week'], sym: ['Intense pelvic pressure', 'Mucus plug may release', 'Lightning crotch', 'Difficulty walking'], prep: [{ i: 'calendar', t: 'Weekly OB appointments', d: 'Cervical checks begin' }, { i: 'book', t: 'Finish childbirth classes', d: 'Review notes and breathing techniques' }, { i: 'plate', t: 'Prep freezer meals', d: 'Future-you will thank you' }] },
  37: { trim: 'Third', dev: ['Baby considered "early term"', 'Full lung function developing', 'Practicing breathing motions more'], sym: ['Water breaking possible', 'Stronger contractions', 'Diarrhea (body preparing)', 'Nesting instinct peaks'], prep: [{ i: 'siren', t: 'Know labor signs', d: 'Contractions 5 min apart, water breaking' }, { i: 'phone', t: 'Keep phone charged', d: 'Emergency contacts ready' }, { i: 'bath', t: 'Rest and pamper', d: 'Enjoy the last weeks' }] },
  38: { trim: 'Third', dev: ["Baby's grasp is very strong", 'Most brain development complete', 'Mostly storing fat now'], sym: ['Pelvic pressure', 'Contractions', 'Swollen extremities', 'Fatigue'], prep: [{ i: 'bottle', t: 'Breast pump setup', d: 'Learn how to use before baby arrives' }, { i: 'heart', t: 'Schedule postpartum support', d: 'Partner leave, doula, meal trains' }, { i: 'home', t: "Prep baby's sleep space", d: 'Bassinet near your bed ready' }] },
  39: { trim: 'Third', dev: ['Baby is officially full term', 'All organ systems ready for life outside', 'Fat still accumulating for temperature control'], sym: ['Dilation beginning', 'Bloody show possible', 'Stronger Braxton Hicks', 'Extreme fatigue'], prep: [{ i: 'bulb', t: 'Install baby monitor', d: 'Set up nursery tech' }, { i: 'pencil', t: 'Review birth plan with team', d: "Make sure everyone's aligned" }, { i: 'drop', t: 'Clean + sanitize bottles', d: 'Ready for use on day one' }] },
  40: { trim: 'Third', dev: ['Your due date!', 'Baby fully developed and ready', 'Placenta aging — induction may be considered soon'], sym: ['Active labor signs possible', 'Water breaking', 'Regular contractions', 'Intense anticipation'], prep: [{ i: 'hourglass', t: 'Stay patient', d: 'Only 5% of babies arrive on their due date' }, { i: 'car', t: 'Final hospital bag check', d: 'Everything ready for launch' }, { i: 'candle', t: 'Practice relaxation', d: 'Hypnobirthing, meditation, partner massage' }] },
  41: { trim: 'Overdue', dev: ['Baby continues to gain fat', 'Placenta still functioning but aging', 'Amniotic fluid decreasing slowly'], sym: ['Intense nesting', 'Frustration with waiting', 'More cervical checks', 'Induction discussions'], prep: [{ i: 'stethoscope', t: 'Monitoring tests', d: "NST and ultrasound to check baby's wellbeing" }, { i: 'clipboard', t: 'Discuss induction options', d: 'Pros, cons, timing with your provider' }, { i: 'walk', t: 'Light movement', d: 'Walks may help labor progress' }] },
  42: { trim: 'Overdue', dev: ['Post-term pregnancy officially', 'Induction strongly recommended', 'Baby continues to thrive under monitoring'], sym: ['Induction likely', 'Extra monitoring', 'Exhaustion', 'Emotional readiness'], prep: [{ i: 'home', t: 'Induction plan', d: 'Discuss methods: Pitocin, balloon, breaking water' }, { i: 'phone', t: 'Close contact with OB', d: 'Daily or more frequent checks' }, { i: 'heart', t: 'Mental preparation', d: "Any day now — you've got this" }] },
}

export function getWeekContent(week: number): WeekContent {
  const w = Math.max(1, Math.min(42, week))
  return weekContent[w]
}
