import type { DailyCard } from './types'

// Women's-general "message" cards for the cycle journey. Whole-woman wellness —
// the cycle (phases, PMS, period, ovulation, hormones), the body, rest, stress,
// self-worth, identity — deliberately NOT pregnancy-specific. Tags come from the
// shared 15-tag vocabulary; the pregnancy-only 'birth' tag is never used here.
export const PREPREGNANCY_CARDS: DailyCard[] = [
  { id: 'pc_001', mode: 'pre-pregnancy', color: 'coral', tags: ['body', 'reassurance', 'strength'],
    text: "The cramp, the ache, the heaviness — it's your body doing quiet, ancient work. Be gentle with the one carrying you." },
  { id: 'pc_002', mode: 'pre-pregnancy', color: 'yellow', tags: ['joy', 'wonder'],
    text: "Your body keeps a rhythm older than any calendar. Some days that's worth pausing to marvel at." },
  { id: 'pc_003', mode: 'pre-pregnancy', color: 'lilac', tags: ['fear', 'reassurance', 'calm'],
    text: "You don't need to have it all figured out today. Uncertainty is not the same as being lost." },
  { id: 'pc_004', mode: 'pre-pregnancy', color: 'blue', tags: ['tired', 'reassurance'],
    text: "Low-energy days aren't wasted days. Your body is asking for rest, and rest is an answer, not a failure." },
  { id: 'pc_005', mode: 'pre-pregnancy', color: 'pink', tags: ['overwhelmed', 'calm'],
    text: "You can only hold one moment at a time. Set the rest down for now — it will still be there when you're ready." },
  { id: 'pc_006', mode: 'pre-pregnancy', color: 'green', tags: ['gratitude', 'wonder'],
    text: "For no reason at all, let yourself notice one small good thing today. Your attention is a kind of gratitude." },
  { id: 'pc_007', mode: 'pre-pregnancy', color: 'peach', tags: ['partner', 'connection'],
    text: "You don't have to explain a feeling fully for it to be worth telling someone who loves you." },
  { id: 'pc_008', mode: 'pre-pregnancy', color: 'lilac', tags: ['identity', 'emotion'],
    text: "You are allowed to be many things at once — soft and strong, unsure and capable. All of it is you." },
  { id: 'pc_009', mode: 'pre-pregnancy', color: 'coral', tags: ['fear', 'strength'],
    text: "Fear doesn't mean you're doing it wrong. Usually it means you care about how this turns out." },
  { id: 'pc_010', mode: 'pre-pregnancy', color: 'yellow', tags: ['body', 'joy'],
    text: "When your energy rises this week, follow it. Your body is telling you it's ready to move, make, and begin." },
  { id: 'pc_011', mode: 'pre-pregnancy', color: 'blue', tags: ['body', 'tired', 'calm'],
    text: "That bone-deep tiredness before your period isn't laziness. It's your body lowering the volume so you'll rest." },
  { id: 'pc_012', mode: 'pre-pregnancy', color: 'lilac', tags: ['emotion', 'overwhelmed'],
    text: "Crying easily this week isn't a malfunction. Your hormones just turned the volume up on a heart that was always this big." },
  { id: 'pc_013', mode: 'pre-pregnancy', color: 'pink', tags: ['joy', 'connection'],
    text: "Reach out to someone today, even briefly. Connection is one of the oldest medicines there is." },
  { id: 'pc_014', mode: 'pre-pregnancy', color: 'green', tags: ['strength', 'gratitude'],
    text: "You have carried more than you thought you could, more times than you give yourself credit for." },
  { id: 'pc_015', mode: 'pre-pregnancy', color: 'peach', tags: ['tired', 'reassurance', 'calm'],
    text: "There's no prize for pushing through exhaustion. Lie down. The list can wait a day." },
  { id: 'pc_016', mode: 'pre-pregnancy', color: 'blue', tags: ['fear', 'calm'],
    text: "The worry loop at 3am feels true because it's loud, not because it's accurate. Morning tends to disagree." },
  { id: 'pc_017', mode: 'pre-pregnancy', color: 'coral', tags: ['partner', 'reassurance'],
    text: "It's okay to need someone to just sit with you tonight instead of fixing anything." },
  { id: 'pc_018', mode: 'pre-pregnancy', color: 'yellow', tags: ['wonder', 'identity'],
    text: "You became yourself slowly, mostly without noticing. You're still becoming — that's not a flaw, it's the whole point." },
  { id: 'pc_019', mode: 'pre-pregnancy', color: 'blue', tags: ['body', 'strength'],
    text: "Every month your body renews, releases, and begins again without being asked. None of that is small." },
  { id: 'pc_020', mode: 'pre-pregnancy', color: 'lilac', tags: ['overwhelmed', 'reassurance'],
    text: "The to-do list will still be there tomorrow. Today, keeping yourself going was enough — and you did it." },
  { id: 'pc_021', mode: 'pre-pregnancy', color: 'pink', tags: ['body', 'wonder'],
    text: "Learning your own rhythm — when you rise, when you retreat — is a quiet superpower most people never develop." },
  { id: 'pc_022', mode: 'pre-pregnancy', color: 'green', tags: ['emotion', 'connection'],
    text: "You can feel two things at once — hopeful and scared, tired and grateful. Neither one cancels the other out." },
  { id: 'pc_023', mode: 'pre-pregnancy', color: 'peach', tags: ['gratitude', 'joy'],
    text: "Somewhere in today, however small, there was a moment worth keeping. Let yourself notice it before it passes." },
  { id: 'pc_024', mode: 'pre-pregnancy', color: 'green', tags: ['fear', 'reassurance'],
    text: "You're allowed to want something badly and be frightened of it at the same time. Wanting is not weakness." },
  { id: 'pc_025', mode: 'pre-pregnancy', color: 'coral', tags: ['body', 'overwhelmed'],
    text: "When your body feels like a stranger this week, remember: it's not working against you. It's working, full stop." },
  { id: 'pc_026', mode: 'pre-pregnancy', color: 'yellow', tags: ['strength', 'identity'],
    text: "You are not behind. There is no schedule for a life, only the pace that's honestly yours." },
  { id: 'pc_027', mode: 'pre-pregnancy', color: 'blue', tags: ['calm', 'reassurance'],
    text: "Take one slow breath. Not to fix anything — just to remind your body it's safe to soften for a moment." },
  { id: 'pc_028', mode: 'pre-pregnancy', color: 'lilac', tags: ['identity', 'reassurance'],
    text: "Coming back to yourself after a hard stretch isn't starting over. It's finding your way home to someone who was always there." },
  { id: 'pc_029', mode: 'pre-pregnancy', color: 'pink', tags: ['emotion', 'calm'],
    text: "Not every feeling needs a name or a reason. Sometimes you just feel it, let it pass through, and carry on." },
  { id: 'pc_030', mode: 'pre-pregnancy', color: 'green', tags: ['joy', 'gratitude'],
    text: "Delight is not frivolous. Chasing a small joy today is a serious act of taking care of yourself." },
  { id: 'pc_031', mode: 'pre-pregnancy', color: 'peach', tags: ['tired', 'calm'],
    text: "Slowing down when your body asks isn't falling behind. It's listening — and listening is a skill worth keeping." },
  { id: 'pc_032', mode: 'pre-pregnancy', color: 'coral', tags: ['strength', 'reassurance'],
    text: "On the days you feel least capable, you are still the same woman who has gotten through every hard day so far." },
  { id: 'pc_033', mode: 'pre-pregnancy', color: 'yellow', tags: ['wonder', 'joy'],
    text: "Hope is not naïve. It's the quiet, stubborn thing that keeps you moving toward the life you want." },
  { id: 'pc_034', mode: 'pre-pregnancy', color: 'blue', tags: ['overwhelmed', 'calm'],
    text: "You do not have to earn your rest by finishing everything first. Rest is allowed even mid-mess." },
  { id: 'pc_035', mode: 'pre-pregnancy', color: 'lilac', tags: ['partner', 'connection'],
    text: "Letting someone show up for you isn't a burden on them. It's how you let them love you back." },
  { id: 'pc_036', mode: 'pre-pregnancy', color: 'pink', tags: ['body', 'gratitude'],
    text: "Thank your body for something today, even quietly. It has been on your side longer than anyone." },
  { id: 'pc_037', mode: 'pre-pregnancy', color: 'green', tags: ['identity', 'strength'],
    text: "You are the whole person, not the parts of you that feel too much or too little on any given day." },
  { id: 'pc_038', mode: 'pre-pregnancy', color: 'peach', tags: ['reassurance', 'gratitude'],
    text: "You're doing your best with a body and a life that keep changing. That is not a small thing — it's most of it." },
  { id: 'pc_039', mode: 'pre-pregnancy', color: 'coral', tags: ['emotion', 'overwhelmed'],
    text: "If everything feels like too much before your period, it's not you being dramatic. It's real, and it will ease." },
  { id: 'pc_040', mode: 'pre-pregnancy', color: 'yellow', tags: ['joy', 'strength'],
    text: "When your energy peaks mid-cycle, let yourself feel powerful. That confidence is chemistry and it is also true." },
  { id: 'pc_041', mode: 'pre-pregnancy', color: 'blue', tags: ['fear', 'reassurance', 'calm'],
    text: "The unknown feels heaviest when you carry all of it at once. You only have to hold today's part." },
  { id: 'pc_042', mode: 'pre-pregnancy', color: 'lilac', tags: ['calm', 'identity'],
    text: "Time alone isn't selfish. You cannot hear yourself think in a room that's always full of everyone else." },
  { id: 'pc_043', mode: 'pre-pregnancy', color: 'pink', tags: ['connection', 'reassurance'],
    text: "Whatever you're moving through, you are not the first woman to feel it, and you are not doing it alone." },
  { id: 'pc_044', mode: 'pre-pregnancy', color: 'green', tags: ['wonder', 'gratitude'],
    text: "Your body has a wisdom you didn't have to teach it. Trust it a little more than the noise today." },
]
