import type { DailyCard } from './types'

export const PREGNANCY_CARDS: DailyCard[] = [
  { id: 'c_001', mode: 'pregnancy', color: 'coral', tags: ['body', 'reassurance', 'strength'],
    text: "Your body is doing something extraordinary and invisible. Ache is just the sound of it working." },
  { id: 'c_002', mode: 'pregnancy', color: 'yellow', tags: ['joy', 'wonder'],
    text: "Somewhere under your heart, a whole new person is practicing being alive today." },
  { id: 'c_003', mode: 'pregnancy', color: 'lilac', tags: ['fear', 'reassurance', 'calm'],
    text: "You don't have to feel ready. Readiness arrives in the doing, not before it." },
  { id: 'c_004', mode: 'pregnancy', color: 'blue', tags: ['tired', 'reassurance'],
    text: "Rest is not falling behind. Rest is part of the work your body is already doing." },
  { id: 'c_005', mode: 'pregnancy', color: 'pink', tags: ['overwhelmed', 'calm'],
    text: "You can only carry one moment at a time. Set the rest down; it will wait." },
  { id: 'c_006', mode: 'pregnancy', color: 'green', tags: ['gratitude', 'wonder'],
    text: "Today, for no reason at all, let yourself notice how strange and good it is to be growing a person." },
  { id: 'c_007', mode: 'pregnancy', color: 'peach', tags: ['partner', 'connection'],
    text: "You don't have to explain every feeling for it to be worth sharing out loud with someone who loves you." },
  { id: 'c_008', mode: 'pregnancy', color: 'charcoal', tags: ['identity', 'emotion'],
    text: "You're allowed to still be exactly yourself while becoming someone new. Both things are true at once." },
  { id: 'c_009', mode: 'pregnancy', color: 'coral', tags: ['fear', 'strength'],
    text: "Fear doesn't mean you're doing it wrong. It usually means you're doing something that matters." },
  { id: 'c_010', mode: 'pregnancy', color: 'yellow', tags: ['birth', 'reassurance'],
    text: "Your birth doesn't have to look like anyone else's to be right for you and your baby." },
  { id: 'c_011', mode: 'pregnancy', color: 'blue', tags: ['body', 'tired', 'calm'],
    text: "That heaviness in your legs tonight is a receipt for the work your body did today. Put your feet up." },
  { id: 'c_012', mode: 'pregnancy', color: 'lilac', tags: ['emotion', 'overwhelmed'],
    text: "Crying at a commercial isn't a malfunction. Your heart just got a bigger volume dial for a while." },
  { id: 'c_013', mode: 'pregnancy', color: 'pink', tags: ['joy', 'connection'],
    text: "The first flutter, the first kick, the first hiccup — you're already learning this person's language." },
  { id: 'c_014', mode: 'pregnancy', color: 'green', tags: ['strength', 'gratitude'],
    text: "You have carried more than you thought you could, more times than you're giving yourself credit for." },
  { id: 'c_015', mode: 'pregnancy', color: 'peach', tags: ['tired', 'reassurance', 'calm'],
    text: "There is no prize for staying upright through exhaustion. Lie down. The laundry can wait a day." },
  { id: 'c_016', mode: 'pregnancy', color: 'charcoal', tags: ['fear', 'calm'],
    text: "The worry loop at 3am feels true because it's loud, not because it's accurate. Morning will say otherwise." },
  { id: 'c_017', mode: 'pregnancy', color: 'coral', tags: ['partner', 'reassurance'],
    text: "It's okay to need your partner to just sit with you instead of fixing anything tonight." },
  { id: 'c_018', mode: 'pregnancy', color: 'yellow', tags: ['wonder', 'identity'],
    text: "You are becoming a mother the same way you became yourself — slowly, and mostly without noticing." },
  { id: 'c_019', mode: 'pregnancy', color: 'blue', tags: ['body', 'strength'],
    text: "Your ribs are moving to make room. Your heart is pumping for two. None of this is small." },
  { id: 'c_020', mode: 'pregnancy', color: 'lilac', tags: ['overwhelmed', 'reassurance'],
    text: "The to-do list will still be there tomorrow. Your only job today was to keep growing a person, and you did." },
  { id: 'c_021', mode: 'pregnancy', color: 'pink', tags: ['birth', 'strength'],
    text: "Your body has been rehearsing for this moment since the day it started. Trust the rehearsal." },
  { id: 'c_022', mode: 'pregnancy', color: 'green', tags: ['emotion', 'connection'],
    text: "You can feel two things at once — terrified and thrilled, exhausted and grateful. Neither cancels the other out." },
  { id: 'c_023', mode: 'pregnancy', color: 'peach', tags: ['gratitude', 'joy'],
    text: "Somewhere in today, however small, there was a moment worth keeping. Let yourself notice it." },
  { id: 'c_024', mode: 'pregnancy', color: 'charcoal', tags: ['fear', 'reassurance'],
    text: "Every question you're asking yourself right now, other mothers have asked too, and made it through." },
  { id: 'c_025', mode: 'pregnancy', color: 'coral', tags: ['identity', 'strength'],
    text: "You don't lose yourself in this. You find out what else you're made of." },
  { id: 'c_026', mode: 'pregnancy', color: 'yellow', tags: ['wonder', 'joy'],
    text: "A heartbeat that didn't exist a year ago is keeping time inside you right now. Let that be enough for today." },
  { id: 'c_027', mode: 'pregnancy', color: 'blue', tags: ['tired', 'body'],
    text: "Growing bones and lungs and a whole nervous system takes energy. Of course you're tired. That's the job." },
  { id: 'c_028', mode: 'pregnancy', color: 'lilac', tags: ['partner', 'connection'],
    text: "Let your partner in on the small stuff too — not just the big scary parts. Connection likes the ordinary moments." },
  { id: 'c_029', mode: 'pregnancy', color: 'pink', tags: ['calm', 'reassurance'],
    text: "Breathe out longer than you breathe in. Your body already knows how to find calm — just ask it." },
  { id: 'c_030', mode: 'pregnancy', color: 'green', tags: ['overwhelmed', 'strength'],
    text: "You're not behind. There's no schedule for feeling ready to become a parent — you're already on time." },
  { id: 'c_031', mode: 'pregnancy', color: 'peach', tags: ['emotion', 'gratitude'],
    text: "Tenderness toward yourself is not indulgent right now. It's the least you're owed." },
  { id: 'c_032', mode: 'pregnancy', color: 'charcoal', tags: ['birth', 'fear'],
    text: "You don't need to have it all figured out. The people around you on the day will help you figure out the rest." },
  { id: 'c_033', mode: 'pregnancy', color: 'coral', tags: ['joy', 'identity'],
    text: "The version of you that exists after this baby arrives gets to keep every part of you that you love." },
  { id: 'c_034', mode: 'pregnancy', color: 'yellow', tags: ['wonder', 'connection'],
    text: "Somewhere in there, a heart the size of a poppy seed learned to beat entirely on its own. Marvel at that for a second." },
  { id: 'c_035', mode: 'pregnancy', color: 'blue', tags: ['strength', 'reassurance'],
    text: "You are more capable than the worst day makes you feel. Today's hard doesn't define the whole story." },
  { id: 'c_036', mode: 'pregnancy', color: 'lilac', tags: ['tired', 'calm'],
    text: "A nap is not giving up. A nap is exactly what pregnant bodies are built to ask for and deserve." },
  { id: 'c_037', mode: 'pregnancy', color: 'pink', tags: ['fear', 'partner'],
    text: "Say the scary thought out loud to someone who loves you. Fear shrinks a little every time it's spoken." },
  { id: 'c_038', mode: 'pregnancy', color: 'green', tags: ['gratitude', 'connection'],
    text: "Someone, somewhere today, is glad you exist and gladder still that this baby is coming. Let that in." },
  { id: 'c_039', mode: 'pregnancy', color: 'peach', tags: ['body', 'wonder'],
    text: "Your skin is stretching to hold a whole new life. Stretch marks are just proof of the stretching, not a flaw." },
  { id: 'c_040', mode: 'pregnancy', color: 'charcoal', tags: ['overwhelmed', 'calm'],
    text: "You don't need an answer for everything today. Uncertainty and calm can share the same room." },
  { id: 'c_041', mode: 'pregnancy', color: 'coral', tags: ['emotion', 'strength'],
    text: "Feeling fragile and feeling strong aren't opposites here — most days you'll be both before lunch." },
  { id: 'c_042', mode: 'pregnancy', color: 'yellow', tags: ['identity', 'joy'],
    text: "You get to define what a good mother looks like for you. No one else's version is the only right one." },
  { id: 'c_043', mode: 'pregnancy', color: 'blue', tags: ['birth', 'calm'],
    text: "Whatever the birth ends up looking like, the goal is simple: you and your baby, met safely on the other side." },
  { id: 'c_044', mode: 'pregnancy', color: 'lilac', tags: ['reassurance', 'wonder'],
    text: "You will look back on this exact, ordinary, hard day and remember it as part of how this baby came to be." },
]
