import type { DailyQuestion } from './types'
export { PREPREGNANCY_CARDS } from './cards.prePregnancy'

// Women's-general daily check-in questions for the cycle journey. Spans the
// menstrual cycle (energy across phases, PMS, period, ovulation) AND whole-woman
// wellbeing (body image, rest, stress, self-worth, hormones) — deliberately NOT
// pregnancy-specific. Tags come from the shared 15-tag vocabulary in tags.ts;
// the pregnancy-only 'birth' tag is intentionally never used here.
export const PREPREGNANCY_QUESTIONS: DailyQuestion[] = [
  { id: 'pq_001', mode: 'pre-pregnancy',
    prompt: "How's your body treating you today?",
    options: [
      { label: 'Crampy',    tags: ['body', 'reassurance'] },
      { label: 'Energized', tags: ['body', 'joy'] },
      { label: 'Drained',   tags: ['tired', 'reassurance'] },
      { label: 'Restless',  tags: ['body', 'overwhelmed'] },
    ] },
  { id: 'pq_002', mode: 'pre-pregnancy',
    prompt: "What's loudest in your head right now?",
    options: [
      { label: 'Worry',       tags: ['fear', 'reassurance'] },
      { label: 'Excitement',  tags: ['joy', 'wonder'] },
      { label: 'To-do lists', tags: ['overwhelmed', 'calm'] },
      { label: 'Nothing much',tags: ['calm'] },
    ] },
  { id: 'pq_003', mode: 'pre-pregnancy',
    prompt: "How did you sleep last night?",
    options: [
      { label: 'Barely',            tags: ['tired', 'reassurance'] },
      { label: 'In pieces',         tags: ['tired', 'body'] },
      { label: 'Surprisingly well', tags: ['gratitude', 'calm'] },
      { label: 'Wide awake at 3am',  tags: ['fear', 'overwhelmed'] },
    ] },
  { id: 'pq_004', mode: 'pre-pregnancy',
    prompt: "What do you need most from the people around you today?",
    options: [
      { label: 'Someone to listen', tags: ['partner', 'connection'] },
      { label: 'Space to just be',  tags: ['calm', 'identity'] },
      { label: 'A little help',     tags: ['overwhelmed', 'reassurance'] },
      { label: 'To feel seen',      tags: ['connection', 'emotion'] },
    ] },
  { id: 'pq_005', mode: 'pre-pregnancy',
    prompt: "Where's your energy today?",
    options: [
      { label: 'Running high',   tags: ['body', 'strength'] },
      { label: 'Steady',         tags: ['calm', 'gratitude'] },
      { label: 'Low and quiet',  tags: ['tired', 'reassurance'] },
      { label: 'All over the place', tags: ['emotion', 'overwhelmed'] },
    ] },
  { id: 'pq_006', mode: 'pre-pregnancy',
    prompt: "What's your relationship with your body like today?",
    options: [
      { label: 'Grateful',   tags: ['body', 'gratitude'] },
      { label: 'Frustrated', tags: ['body', 'overwhelmed'] },
      { label: 'In tune',    tags: ['body', 'calm'] },
      { label: 'A stranger to it', tags: ['body', 'identity'] },
    ] },
  { id: 'pq_007', mode: 'pre-pregnancy',
    prompt: "How's your heart today?",
    options: [
      { label: 'Tender',      tags: ['emotion', 'reassurance'] },
      { label: 'Light',       tags: ['joy', 'gratitude'] },
      { label: 'Heavy',       tags: ['emotion', 'overwhelmed'] },
      { label: 'Hard to name',tags: ['emotion', 'calm'] },
    ] },
  { id: 'pq_008', mode: 'pre-pregnancy',
    prompt: "What would feel like real care right now?",
    options: [
      { label: 'Rest',            tags: ['tired', 'calm'] },
      { label: 'Moving my body',  tags: ['body', 'strength'] },
      { label: 'A good cry',      tags: ['emotion', 'reassurance'] },
      { label: 'Time alone',      tags: ['calm', 'identity'] },
    ] },
  { id: 'pq_009', mode: 'pre-pregnancy',
    prompt: "How are you feeling about where you are in life right now?",
    options: [
      { label: 'Hopeful',   tags: ['joy', 'wonder'] },
      { label: 'Impatient', tags: ['fear', 'overwhelmed'] },
      { label: 'Content',   tags: ['calm', 'gratitude'] },
      { label: 'Uncertain', tags: ['fear', 'reassurance'] },
    ] },
  { id: 'pq_010', mode: 'pre-pregnancy',
    prompt: "What are you being hardest on yourself about today?",
    options: [
      { label: 'My body',        tags: ['body', 'reassurance'] },
      { label: 'Not doing enough',tags: ['overwhelmed', 'reassurance'] },
      { label: 'My moods',       tags: ['emotion', 'reassurance'] },
      { label: 'Nothing, today', tags: ['calm', 'gratitude'] },
    ] },
  { id: 'pq_011', mode: 'pre-pregnancy',
    prompt: "How connected do you feel to yourself lately?",
    options: [
      { label: 'Very',             tags: ['identity', 'strength'] },
      { label: 'Losing the thread',tags: ['identity', 'overwhelmed'] },
      { label: 'Coming back to it', tags: ['identity', 'reassurance'] },
      { label: 'Searching',        tags: ['identity', 'wonder'] },
    ] },
  { id: 'pq_012', mode: 'pre-pregnancy',
    prompt: "What's your mood asking for today?",
    options: [
      { label: 'Gentleness',  tags: ['reassurance', 'calm'] },
      { label: 'A little fun',tags: ['joy', 'connection'] },
      { label: 'Quiet',       tags: ['calm', 'identity'] },
      { label: 'To be held',  tags: ['partner', 'connection'] },
    ] },
  { id: 'pq_013', mode: 'pre-pregnancy',
    prompt: "How's the wait — for whatever you're waiting on — sitting with you?",
    options: [
      { label: 'Hard',       tags: ['fear', 'reassurance'] },
      { label: 'Patient',    tags: ['calm', 'strength'] },
      { label: 'Hopeful',    tags: ['wonder', 'joy'] },
      { label: 'Exhausting', tags: ['tired', 'overwhelmed'] },
    ] },
  { id: 'pq_014', mode: 'pre-pregnancy',
    prompt: "What's true about you today, even on a low day?",
    options: [
      { label: "I'm strong",     tags: ['strength', 'reassurance'] },
      { label: "I'm doing my best",tags: ['reassurance', 'gratitude'] },
      { label: "I'm still here",  tags: ['strength', 'identity'] },
      { label: "I'm allowed to rest",tags: ['tired', 'calm'] },
    ] },
  { id: 'pq_015', mode: 'pre-pregnancy',
    prompt: "How's your stress today?",
    options: [
      { label: 'Simmering',    tags: ['overwhelmed', 'calm'] },
      { label: 'Under control',tags: ['calm', 'strength'] },
      { label: 'Boiling over', tags: ['overwhelmed', 'reassurance'] },
      { label: 'Quiet, for once',tags: ['calm', 'gratitude'] },
    ] },
  { id: 'pq_016', mode: 'pre-pregnancy',
    prompt: "What do you wish someone would say to you right now?",
    options: [
      { label: "You're doing enough", tags: ['reassurance', 'overwhelmed'] },
      { label: "I'm proud of you",    tags: ['gratitude', 'strength'] },
      { label: "You're not alone",    tags: ['connection', 'reassurance'] },
      { label: "Take your time",      tags: ['calm', 'reassurance'] },
    ] },
  { id: 'pq_017', mode: 'pre-pregnancy',
    prompt: "How does your body feel about movement today?",
    options: [
      { label: 'Ready to go',   tags: ['body', 'strength'] },
      { label: 'Gentle only',   tags: ['body', 'calm'] },
      { label: 'Not today',     tags: ['tired', 'reassurance'] },
      { label: 'Craving fresh air', tags: ['body', 'joy'] },
    ] },
  { id: 'pq_018', mode: 'pre-pregnancy',
    prompt: "What's one thing you're quietly grateful for today?",
    options: [
      { label: 'My people',      tags: ['connection', 'gratitude'] },
      { label: 'A small comfort',tags: ['calm', 'gratitude'] },
      { label: 'My own resilience',tags: ['strength', 'gratitude'] },
      { label: 'Just today itself',tags: ['wonder', 'gratitude'] },
    ] },
  { id: 'pq_019', mode: 'pre-pregnancy',
    prompt: "How are your feelings showing up today?",
    options: [
      { label: 'Close to the surface',tags: ['emotion', 'reassurance'] },
      { label: 'Bottled up',          tags: ['emotion', 'overwhelmed'] },
      { label: 'Calm and even',       tags: ['calm', 'emotion'] },
      { label: 'Surprising me',       tags: ['emotion', 'wonder'] },
    ] },
  { id: 'pq_020', mode: 'pre-pregnancy',
    prompt: "What kind of day are you hoping to give yourself?",
    options: [
      { label: 'A soft one',     tags: ['calm', 'reassurance'] },
      { label: 'A productive one',tags: ['strength', 'identity'] },
      { label: 'A joyful one',    tags: ['joy', 'connection'] },
      { label: "One I don't overthink", tags: ['calm', 'overwhelmed'] },
    ] },
  { id: 'pq_021', mode: 'pre-pregnancy',
    prompt: "Where could you be a little kinder to yourself today?",
    options: [
      { label: 'About my body',    tags: ['body', 'reassurance'] },
      { label: 'About my pace',    tags: ['tired', 'calm'] },
      { label: 'About my choices', tags: ['identity', 'reassurance'] },
      { label: 'About everything', tags: ['overwhelmed', 'reassurance'] },
    ] },
  { id: 'pq_022', mode: 'pre-pregnancy',
    prompt: "What's your body trying to tell you this week?",
    options: [
      { label: 'Slow down',      tags: ['tired', 'reassurance'] },
      { label: "I'm capable",    tags: ['strength', 'body'] },
      { label: 'Pay attention',  tags: ['body', 'wonder'] },
      { label: 'Be gentle with me',tags: ['body', 'calm'] },
    ] },
]
