import type { DailyQuestion } from './types'
export { PREGNANCY_CARDS } from './cards.pregnancy'

export const PREGNANCY_QUESTIONS: DailyQuestion[] = [
  { id: 'q_001', mode: 'pregnancy',
    prompt: "How's your body treating you today?",
    options: [
      { label: 'Achy',      tags: ['body', 'reassurance'] },
      { label: 'Energized', tags: ['body', 'joy'] },
      { label: 'Exhausted', tags: ['tired', 'reassurance'] },
      { label: 'Numb',      tags: ['emotion', 'overwhelmed'] },
    ] },
  { id: 'q_002', mode: 'pregnancy',
    prompt: "What's loudest in your head right now?",
    options: [
      { label: 'Worry',      tags: ['fear', 'reassurance'] },
      { label: 'Excitement', tags: ['joy', 'wonder'] },
      { label: 'To-do lists',tags: ['overwhelmed', 'calm'] },
      { label: 'Nothing',    tags: ['calm'] },
    ] },
  { id: 'q_003', mode: 'pregnancy',
    prompt: "How did you sleep last night?",
    options: [
      { label: 'Barely',        tags: ['tired', 'reassurance'] },
      { label: 'In pieces',     tags: ['tired', 'body'] },
      { label: 'Surprisingly well', tags: ['gratitude', 'calm'] },
      { label: 'Full of dreams', tags: ['wonder', 'emotion'] },
    ] },
  { id: 'q_004', mode: 'pregnancy',
    prompt: "What do you need most from the people around you today?",
    options: [
      { label: 'Someone to listen',  tags: ['partner', 'connection'] },
      { label: 'Space to just be',   tags: ['calm', 'identity'] },
      { label: 'A little help',      tags: ['overwhelmed', 'reassurance'] },
      { label: 'To be celebrated',   tags: ['joy', 'gratitude'] },
    ] },
  { id: 'q_005', mode: 'pregnancy',
    prompt: "How are you feeling about the birth lately?",
    options: [
      { label: 'Nervous',      tags: ['birth', 'fear'] },
      { label: 'Curious',      tags: ['birth', 'wonder'] },
      { label: 'Prepared',     tags: ['birth', 'strength'] },
      { label: "Trying not to think about it", tags: ['birth', 'overwhelmed'] },
    ] },
  { id: 'q_006', mode: 'pregnancy',
    prompt: "What's your relationship with your changing body like today?",
    options: [
      { label: 'Grateful',     tags: ['body', 'gratitude'] },
      { label: 'Unfamiliar',   tags: ['body', 'identity'] },
      { label: 'In awe',       tags: ['body', 'wonder'] },
      { label: 'Frustrated',   tags: ['body', 'overwhelmed'] },
    ] },
  { id: 'q_007', mode: 'pregnancy',
    prompt: "How connected do you feel to the baby right now?",
    options: [
      { label: 'Very',         tags: ['connection', 'joy'] },
      { label: 'Some days more than others', tags: ['connection', 'reassurance'] },
      { label: 'Still getting there', tags: ['connection', 'reassurance'] },
      { label: 'Overwhelmed by it', tags: ['connection', 'overwhelmed'] },
    ] },
  { id: 'q_008', mode: 'pregnancy',
    prompt: "What's something you're grateful for this week?",
    options: [
      { label: 'My support system', tags: ['gratitude', 'connection'] },
      { label: 'My body',            tags: ['gratitude', 'body'] },
      { label: 'A quiet moment',     tags: ['gratitude', 'calm'] },
      { label: "Hard to think of one right now", tags: ['gratitude', 'reassurance'] },
    ] },
  { id: 'q_009', mode: 'pregnancy',
    prompt: "How's your partner showing up for you lately?",
    options: [
      { label: 'Really well',    tags: ['partner', 'gratitude'] },
      { label: "Trying, but it's not quite enough", tags: ['partner', 'emotion'] },
      { label: "I haven't asked for what I need", tags: ['partner', 'overwhelmed'] },
      { label: 'We feel like a team', tags: ['partner', 'connection'] },
    ] },
  { id: 'q_010', mode: 'pregnancy',
    prompt: "What word best describes today?",
    options: [
      { label: 'Heavy',    tags: ['tired', 'overwhelmed'] },
      { label: 'Hopeful',  tags: ['joy', 'strength'] },
      { label: 'Tender',   tags: ['emotion', 'connection'] },
      { label: 'Steady',   tags: ['calm', 'strength'] },
    ] },
  { id: 'q_011', mode: 'pregnancy',
    prompt: "How do you feel about who you're becoming?",
    options: [
      { label: 'Curious',      tags: ['identity', 'wonder'] },
      { label: 'A little lost', tags: ['identity', 'fear'] },
      { label: 'Proud',        tags: ['identity', 'strength'] },
      { label: 'Still myself, plus more', tags: ['identity', 'joy'] },
    ] },
  { id: 'q_012', mode: 'pregnancy',
    prompt: "What's on your mind about the birth plan?",
    options: [
      { label: "I don't have one yet", tags: ['birth', 'overwhelmed'] },
      { label: "I'm holding it loosely", tags: ['birth', 'calm'] },
      { label: "I feel good about it", tags: ['birth', 'reassurance'] },
      { label: "I'm scared it won't go as planned", tags: ['birth', 'fear'] },
    ] },
  { id: 'q_013', mode: 'pregnancy',
    prompt: "How full is your energy tank today?",
    options: [
      { label: 'Empty',        tags: ['tired', 'body'] },
      { label: 'Half full',    tags: ['tired', 'reassurance'] },
      { label: 'Surprisingly full', tags: ['joy', 'strength'] },
      { label: 'Running on adrenaline', tags: ['overwhelmed', 'body'] },
    ] },
  { id: 'q_014', mode: 'pregnancy',
    prompt: "What feeling keeps sneaking up on you this week?",
    options: [
      { label: 'Fear',         tags: ['fear', 'emotion'] },
      { label: 'Joy',          tags: ['joy', 'gratitude'] },
      { label: 'Grief for the old normal', tags: ['emotion', 'identity'] },
      { label: 'Wonder',       tags: ['wonder', 'connection'] },
    ] },
  { id: 'q_015', mode: 'pregnancy',
    prompt: "How are you taking care of yourself today?",
    options: [
      { label: 'Resting',       tags: ['calm', 'body'] },
      { label: 'Barely managing', tags: ['overwhelmed', 'tired'] },
      { label: 'Leaning on others', tags: ['partner', 'connection'] },
      { label: 'Doing something just for me', tags: ['joy', 'identity'] },
    ] },
  { id: 'q_016', mode: 'pregnancy',
    prompt: "What does strength look like for you right now?",
    options: [
      { label: 'Pushing through', tags: ['strength', 'body'] },
      { label: 'Asking for help', tags: ['strength', 'partner'] },
      { label: 'Resting without guilt', tags: ['strength', 'calm'] },
      { label: 'Showing up scared anyway', tags: ['strength', 'fear'] },
    ] },
  { id: 'q_017', mode: 'pregnancy',
    prompt: "How do you feel about your body changing shape?",
    options: [
      { label: 'At peace with it', tags: ['body', 'calm'] },
      { label: 'Still adjusting',  tags: ['body', 'identity'] },
      { label: 'Amazed by it',     tags: ['body', 'wonder'] },
      { label: 'Self-conscious',   tags: ['body', 'emotion'] },
    ] },
  { id: 'q_018', mode: 'pregnancy',
    prompt: "What's your gratitude looking like today?",
    options: [
      { label: 'Big and obvious',   tags: ['gratitude', 'joy'] },
      { label: 'Small and quiet',   tags: ['gratitude', 'calm'] },
      { label: 'Hiding under stress', tags: ['gratitude', 'overwhelmed'] },
      { label: 'Focused on my partner', tags: ['gratitude', 'partner'] },
    ] },
  { id: 'q_019', mode: 'pregnancy',
    prompt: "How do you want to feel by the end of today?",
    options: [
      { label: 'Calm',       tags: ['calm', 'reassurance'] },
      { label: 'Connected',  tags: ['connection', 'partner'] },
      { label: 'Proud of myself', tags: ['strength', 'identity'] },
      { label: 'Just done',  tags: ['tired', 'overwhelmed'] },
    ] },
  { id: 'q_020', mode: 'pregnancy',
    prompt: "What part of this pregnancy feels most like wonder right now?",
    options: [
      { label: 'Feeling the baby move', tags: ['wonder', 'joy'] },
      { label: 'Watching my body change', tags: ['wonder', 'body'] },
      { label: "Imagining who they'll be", tags: ['wonder', 'identity'] },
      { label: "Honestly, I haven't felt it lately", tags: ['wonder', 'reassurance'] },
    ] },
  { id: 'q_021', mode: 'pregnancy',
    prompt: "How are you and your partner connecting these days?",
    options: [
      { label: 'Talking it all through', tags: ['partner', 'connection'] },
      { label: 'Quiet moments together', tags: ['partner', 'calm'] },
      { label: 'A bit distant lately', tags: ['partner', 'emotion'] },
      { label: 'Excited planning together', tags: ['partner', 'joy'] },
    ] },
  { id: 'q_022', mode: 'pregnancy',
    prompt: "What would help you feel more grounded today?",
    options: [
      { label: "A reminder I'm strong enough", tags: ['strength', 'reassurance'] },
      { label: 'Permission to rest', tags: ['tired', 'calm'] },
      { label: 'Someone to talk to', tags: ['connection', 'partner'] },
      { label: 'A moment of gratitude', tags: ['gratitude', 'calm'] },
    ] },
]
