-- Affirmations table with pregnancy phrases
-- Fetched daily by the app, cached in AsyncStorage

CREATE TABLE IF NOT EXISTS affirmations (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  text        TEXT        NOT NULL,
  category    TEXT        NOT NULL DEFAULT 'pregnancy',
  week_min    INT,
  week_max    INT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE affirmations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "affirmations_public_read" ON affirmations
  FOR SELECT USING (true);

-- RPC: returns one affirmation deterministically by day offset
CREATE OR REPLACE FUNCTION get_daily_affirmation(p_category TEXT DEFAULT 'pregnancy')
RETURNS TEXT
LANGUAGE sql
STABLE
AS $$
  SELECT text
  FROM affirmations
  WHERE category = p_category
  ORDER BY id
  OFFSET (EXTRACT(DOY FROM NOW())::INT % (SELECT COUNT(*) FROM affirmations WHERE category = p_category))
  LIMIT 1;
$$;

-- ─── Seed: 300 pregnancy affirmations ────────────────────────────────────────

INSERT INTO affirmations (text, category) VALUES
('Your body knows exactly what to do. Trust it completely.', 'pregnancy'),
('Every day you are growing a miracle. You are extraordinary.', 'pregnancy'),
('You are stronger than you know and braver than you feel.', 'pregnancy'),
('Your baby feels your love with every heartbeat.', 'pregnancy'),
('Rest is productive. Nourishing yourself nourishes your baby.', 'pregnancy'),
('You were made for this. Your instincts are wise.', 'pregnancy'),
('Your emotions are valid. Growing life is hard and beautiful work.', 'pregnancy'),
('You are not alone on this journey. You are held and supported.', 'pregnancy'),
('Every ache and change is your body doing its incredible work.', 'pregnancy'),
('The love you already feel for your baby is real and powerful.', 'pregnancy'),
('Your body has built a human from scratch. That is extraordinary.', 'pregnancy'),
('Be gentle with yourself today. You are doing enough.', 'pregnancy'),
('You are exactly where you are supposed to be right now.', 'pregnancy'),
('Your baby hears your voice and finds comfort in it.', 'pregnancy'),
('Fear is natural. Courage is feeling it and moving forward anyway.', 'pregnancy'),
('This pregnancy is uniquely yours — there is no comparison.', 'pregnancy'),
('You are preparing a safe world for someone who will love you unconditionally.', 'pregnancy'),
('Take a deep breath. You and your baby are okay.', 'pregnancy'),
('Your body is strong, capable, and designed for this.', 'pregnancy'),
('Every craving, every kick, every sleepless night is part of the story.', 'pregnancy'),
('You are becoming someone''s whole world.', 'pregnancy'),
('Trust the process. Your body and your baby are in sync.', 'pregnancy'),
('The way you love your baby already says everything about who you are.', 'pregnancy'),
('Nourish yourself as lovingly as you nourish your baby.', 'pregnancy'),
('You don''t need to be perfect — your baby just needs you.', 'pregnancy'),
('Growth happens slowly, then all at once. You are growing too.', 'pregnancy'),
('Your strength has always been there. Pregnancy is revealing it.', 'pregnancy'),
('Today, let yourself feel joy about what is coming.', 'pregnancy'),
('You are writing the first chapter of someone''s lifelong story.', 'pregnancy'),
('Your intuition about your pregnancy matters. Listen to it.', 'pregnancy'),
('The discomfort is temporary. The love is forever.', 'pregnancy'),
('You are held in the hands of every woman who came before you.', 'pregnancy'),
('Your baby is already learning from your calmness and your courage.', 'pregnancy'),
('Something beautiful is happening inside you right now.', 'pregnancy'),
('You deserve support, rest, and kindness — especially from yourself.', 'pregnancy'),
('Every kick is your baby saying: I''m here, I''m growing, I''m yours.', 'pregnancy'),
('The uncertainty is hard. Your love through it is the constant.', 'pregnancy'),
('You are not just having a baby — you are becoming a mother.', 'pregnancy'),
('What a privilege it is, to be the first home your child ever knows.', 'pregnancy'),
('Today is a good day to be gentle with your body and your heart.', 'pregnancy'),
('You are doing the most important thing there is.', 'pregnancy'),
('Let your body lead. It has wisdom your mind cannot access.', 'pregnancy'),
('You are already the mother your baby needs.', 'pregnancy'),
('One breath at a time. One day at a time. That is enough.', 'pregnancy'),
('Your softness right now is not weakness — it is love made physical.', 'pregnancy'),
('The world is about to know the person you are carrying.', 'pregnancy'),
('You are held, even on the days it doesn''t feel like it.', 'pregnancy'),
('Your courage shows up in the small moments too. All of them count.', 'pregnancy'),
('Slow down. Your only job right now is to grow and be.', 'pregnancy'),
('You are creating life. That is the most powerful thing a person can do.', 'pregnancy'),
('Your baby is safe. You are safe. Breathe.', 'pregnancy'),
('Today''s discomfort is tomorrow''s miracle.', 'pregnancy'),
('You are connected to every mother who ever grew a child. You are not alone.', 'pregnancy'),
('Your body knows the way. Follow it.', 'pregnancy'),
('There is a person in there who already loves you completely.', 'pregnancy'),
('You do not have to have it all figured out. Showing up is enough.', 'pregnancy'),
('Drink water. Rest. That is revolutionary self-care.', 'pregnancy'),
('The aches mean your body is working. It is always, always working for you.', 'pregnancy'),
('You are practicing patience, endurance, and unconditional love all at once.', 'pregnancy'),
('Your baby chose you. That means something.', 'pregnancy'),
('You are doing something your ancestors prayed for. Honor that.', 'pregnancy'),
('There is nothing more powerful than a mother who trusts herself.', 'pregnancy'),
('Even on hard days, you are growing something miraculous.', 'pregnancy'),
('You will forget the hard parts. You will remember the feeling of meeting them.', 'pregnancy'),
('Your body is not broken. It is building.', 'pregnancy'),
('Whatever you felt today — you showed up. That is the whole job.', 'pregnancy'),
('You are safe to feel scared. You are safe to feel excited. Both can be true.', 'pregnancy'),
('The tiredness is real. So is the miracle inside you.', 'pregnancy'),
('You are not behind. You are exactly on time.', 'pregnancy'),
('Trust the kicks. Trust the cravings. Trust your body.', 'pregnancy'),
('Your love for this baby is already changing the world.', 'pregnancy'),
('Take up space. You are growing life — you deserve room.', 'pregnancy'),
('Every stretch mark is your body making room for something eternal.', 'pregnancy'),
('You do not need to earn your rest. Rest is part of the work.', 'pregnancy'),
('The version of you on the other side of this will be unstoppable.', 'pregnancy'),
('You are building a person. That is allowed to be hard and beautiful at the same time.', 'pregnancy'),
('Your baby hears your laugh. Let yourself laugh today.', 'pregnancy'),
('Whatever shape your body takes, it is doing something sacred.', 'pregnancy'),
('There is no right way to feel. All your feelings are valid today.', 'pregnancy'),
('You are more prepared than you think.', 'pregnancy'),
('Your patience right now is teaching your baby what safety feels like.', 'pregnancy'),
('Let the love you feel for your baby remind you how remarkable you are.', 'pregnancy'),
('The world needs the person you are bringing into it.', 'pregnancy'),
('Your heartbeat is the most comforting sound your baby knows.', 'pregnancy'),
('You are allowed to grieve the old version of yourself while welcoming the new.', 'pregnancy'),
('You are not falling apart. You are expanding.', 'pregnancy'),
('Something ancient and wise is happening through you right now.', 'pregnancy'),
('You are worthy of every comfort, every kindness, every gentle word.', 'pregnancy'),
('Your baby is already learning what it feels like to be loved.', 'pregnancy'),
('Rest without guilt. Your body is working even when you are still.', 'pregnancy'),
('Pregnancy is not a performance. It is a relationship — between you and your baby.', 'pregnancy'),
('You are on the edge of one of life''s most profound transformations.', 'pregnancy'),
('The moments of doubt mean you are paying attention. That is good mothering.', 'pregnancy'),
('You do not have to feel grateful every moment. You are allowed to struggle.', 'pregnancy'),
('Your baby will not remember the hard days. They will feel the love you carried.', 'pregnancy'),
('Today you grew another day. That is the win.', 'pregnancy'),
('Let yourself be held — by others, by hope, by the miracle you are carrying.', 'pregnancy'),
('Your story is yours. There is no comparison that applies to you.', 'pregnancy'),
('You have already loved this baby through every hard day. That is real love.', 'pregnancy'),
('You are the bridge between who your baby was and who they will become.', 'pregnancy'),
('What you are carrying is holy. So are you.', 'pregnancy'),
('Your gentleness with yourself teaches your baby gentleness.', 'pregnancy'),
('Everything you need is already inside you.', 'pregnancy'),
('You are not doing this alone. The universe is with you.', 'pregnancy'),
('Be as kind to yourself today as you will be to your baby.', 'pregnancy'),
('The love you feel right now is just the beginning.', 'pregnancy'),
('You are doing beautifully, even on the days you feel like you aren''t.', 'pregnancy'),
('Your body is a home. You have made it warm and safe.', 'pregnancy'),
('Wonder and worry can live side by side. You can hold both.', 'pregnancy'),
('You are being prepared for the greatest role of your life.', 'pregnancy'),
('Every day closer is a gift. Even the uncomfortable ones.', 'pregnancy'),
('Breathe in. Breathe out. Your baby breathes with you.', 'pregnancy'),
('You are not just waiting — you are becoming.', 'pregnancy'),
('The love that started as a feeling is becoming a person.', 'pregnancy'),
('Your body has not failed you. It is rising to something extraordinary.', 'pregnancy'),
('There is a whole human learning who they are because of who you are.', 'pregnancy'),
('Some days the win is just getting through. That is still a win.', 'pregnancy'),
('You are being stretched — physically, emotionally, spiritually. That is growth.', 'pregnancy'),
('Your baby does not need a perfect mother. They need you.', 'pregnancy'),
('The peace you create inside yourself travels to your baby. Rest in peace today.', 'pregnancy'),
('You are growing in every direction — in body, in wisdom, in love.', 'pregnancy'),
('There is no one more qualified to be this baby''s mother than you.', 'pregnancy'),
('Worry is love with nowhere to go. Let some of it go today.', 'pregnancy'),
('You are both anchor and sail — grounded and rising at the same time.', 'pregnancy'),
('The exhaustion you feel is the weight of love. It is real and it is good.', 'pregnancy'),
('You are a miracle carrying a miracle.', 'pregnancy'),
('Trust your body''s rhythm. It has been doing this for generations.', 'pregnancy'),
('You are not lost. You are in the in-between. And that is okay.', 'pregnancy'),
('Today, give yourself credit for every small thing you did right.', 'pregnancy'),
('The waiting is hard. But what is coming is worth every moment of it.', 'pregnancy'),
('Your love is already shaping a whole human life. Let that sink in.', 'pregnancy'),
('You are not falling behind. You are on your own sacred timeline.', 'pregnancy'),
('Even your fears come from love. You care so deeply.', 'pregnancy'),
('Let your body do what it was designed to do. It knows the way.', 'pregnancy'),
('You are in the middle of a transformation that only a few will ever know.', 'pregnancy'),
('You are not just making a baby. You are making a family.', 'pregnancy'),
('The version of love you feel right now has no name — it is just yours.', 'pregnancy'),
('Wherever your baby goes in life, they started from your heartbeat.', 'pregnancy'),
('You do not have to be brave every day. Rest is allowed.', 'pregnancy'),
('Your capacity for love is growing along with your belly.', 'pregnancy'),
('The best thing you can give your baby today is a calm, nourished you.', 'pregnancy'),
('You are writing a love story that started before your baby was even born.', 'pregnancy'),
('You are not small. You are the beginning of something enormous.', 'pregnancy'),
('The days feel long but the season is short. Cherish even the hard parts.', 'pregnancy'),
('Your baby is safe and warm and loved. You are doing that. You.', 'pregnancy'),
('Strength does not always look like power. Sometimes it looks like rest.', 'pregnancy'),
('You are worthy of this baby and this baby is worthy of you.', 'pregnancy'),
('This is not easy, and you are doing it anyway. That is everything.', 'pregnancy'),
('Every moment of discomfort is your body saying: I am here, I am working.', 'pregnancy'),
('You are the first story your baby will know. Make today a gentle chapter.', 'pregnancy'),
('Let yourself feel proud. You are doing something remarkable.', 'pregnancy'),
('Your baby is growing in love as much as in body.', 'pregnancy'),
('All the softness you feel right now? That is becoming your superpower.', 'pregnancy'),
('The love between you and your baby has already changed both of you.', 'pregnancy'),
('You are allowed to not have all the answers. No one does at first.', 'pregnancy'),
('What matters today: you showed up. That is everything.', 'pregnancy'),
('Your baby does not need a flawless mother. They need a present one.', 'pregnancy'),
('Every day of this pregnancy is a day your baby has been loved. All of them.', 'pregnancy'),
('You are doing it — not perfectly, but beautifully.', 'pregnancy'),
('The love you feel right now will only grow. Give yourself permission to feel it.', 'pregnancy'),
('You are a home. And you have made it warm and full of love.', 'pregnancy'),
('Your instincts are already sharper than you know. Trust them.', 'pregnancy'),
('You are exactly the mother this baby needs, in exactly this moment.', 'pregnancy'),
('What is coming is bigger than the fear. Keep going.', 'pregnancy'),
('You are giving your baby the greatest first gift: being wanted.', 'pregnancy'),
('You belong in this story. You were always meant to be in this story.', 'pregnancy'),
('Every night you rest, you are giving your baby your best self tomorrow.', 'pregnancy'),
('There is nothing casual about what you are doing. This is sacred work.', 'pregnancy'),
('You are discovering strengths you did not know you had.', 'pregnancy'),
('Let the love you have for your baby remind you how loved you are too.', 'pregnancy'),
('The world is waiting to meet the person you are growing. So are we.', 'pregnancy'),
('You are more than enough. You always were.', 'pregnancy'),
('Be proud of every day you have carried this pregnancy. Every. Single. One.', 'pregnancy'),
('You are in one of the most beautiful chapters of a human life. Breathe it in.', 'pregnancy'),
('Your baby is counting on you, and you are showing up. That is the whole thing.', 'pregnancy'),
('Even when you feel uncertain, your love is certain. That is what counts.', 'pregnancy'),
('Your softness right now will shape how your baby experiences the world.', 'pregnancy'),
('Nothing about you is broken. Everything about you is becoming.', 'pregnancy'),
('You have carried every hard day with love. Do not forget that.', 'pregnancy'),
('Today, give your baby the gift of your calm.', 'pregnancy'),
('You are building something that will outlive you. How extraordinary is that?', 'pregnancy'),
('Every time you chose rest over guilt, you chose your baby too.', 'pregnancy'),
('You are being changed by love — and that is the most beautiful change.', 'pregnancy'),
('The connection you feel with your baby is real, and it is already profound.', 'pregnancy'),
('You are creating someone who will know what love feels like from day one.', 'pregnancy'),
('Let yourself be amazed by what your body is doing. It deserves your awe.', 'pregnancy'),
('Even the nights you cried, you showed up. That is strength.', 'pregnancy'),
('You have already made it through every hard day. All of them.', 'pregnancy'),
('Your love does not need to be perfect to be powerful.', 'pregnancy'),
('Something new is happening in you that the world has never seen before.', 'pregnancy'),
('The calm you are searching for is available to you. Breathe toward it.', 'pregnancy'),
('Your baby is growing in exactly the right place — with you.', 'pregnancy'),
('Today, honor your body. It is doing the work of a lifetime.', 'pregnancy'),
('Every bit of care you give yourself goes directly to your baby. You are one.', 'pregnancy'),
('You are not alone in the waiting. We are waiting with you.', 'pregnancy'),
('You are enough. You always have been. Pregnancy is just proving it.', 'pregnancy'),
('The love that started in your heart is becoming a whole person. Hold that.', 'pregnancy'),
('You are a warrior, a nurturer, a creator — all at once. Every day.', 'pregnancy'),
('Your journey does not have to look like anyone else''s. This one is yours.', 'pregnancy'),
('You are building something beautiful. Keep going.', 'pregnancy'),
('Let today be a day you give yourself grace, not judgment.', 'pregnancy'),
('Your baby is growing in the safest place they will ever know — you.', 'pregnancy'),
('The questions you ask mean you are paying attention. You are a good mother.', 'pregnancy'),
('You are not just surviving this. You are learning to thrive through it.', 'pregnancy'),
('You are the beginning of everything your baby will ever know about love.', 'pregnancy'),
('Every breath you take is shared. You are never alone in this.', 'pregnancy'),
('Whatever today brought, you carried it. And your baby felt your strength.', 'pregnancy'),
('You are in the sacred middle — not who you were, not yet who you will be.', 'pregnancy'),
('What you are doing is the oldest, most powerful act in human history.', 'pregnancy'),
('Your baby already knows the rhythm of your love. It is their first song.', 'pregnancy'),
('You are not failing. You are learning in real time, in the most beautiful way.', 'pregnancy'),
('There is a whole life ahead — yours and theirs — and it begins with you, today.', 'pregnancy'),
('You are exactly where you need to be. Trust the unfolding.', 'pregnancy'),
('The version of you that exists on the other side of this is radiant.', 'pregnancy'),
('Your courage is quiet and constant and remarkable.', 'pregnancy'),
('You have what it takes. You always did.', 'pregnancy'),
('What you are feeling is love, and love is never wrong.', 'pregnancy'),
('You are the first gift your baby will ever receive.', 'pregnancy'),
('Today''s strength becomes tomorrow''s story. Keep writing yours.', 'pregnancy'),
('You are held by something larger than your fear.', 'pregnancy'),
('Your baby is lucky — not because you are perfect, but because you care so much.', 'pregnancy'),
('Let today be soft. Tomorrow can be bold. Both are allowed.', 'pregnancy'),
('The world becomes a better place the moment your child enters it.', 'pregnancy'),
('You have already changed everything. And your baby isn''t even here yet.', 'pregnancy'),
('Every day of this pregnancy is a day you chose love. Remember that.', 'pregnancy'),
('You are more powerful than you feel on your hardest days.', 'pregnancy'),
('Your capacity to love is bigger than you have ever known. This is just the beginning.', 'pregnancy'),
('You are not late, not behind, not wrong. You are right on time.', 'pregnancy'),
('Wherever you are today, your baby is with you. You are never truly alone.', 'pregnancy'),
('Your kindness to yourself teaches your baby what self-worth looks like.', 'pregnancy'),
('The love between you has no end. It started before they were born.', 'pregnancy'),
('You are the answer to a prayer your baby doesn''t even know they''re praying.', 'pregnancy'),
('Everything you are learning right now is preparing you for the greatest love.', 'pregnancy'),
('You are the most important person in a very important story.', 'pregnancy'),
('Be gentle today. Be brave tomorrow. Both things are true.', 'pregnancy'),
('Your baby is growing into exactly the person they are meant to be. So are you.', 'pregnancy'),
('You are not failing when you struggle. You are growing when it is hardest.', 'pregnancy'),
('The person inside you will carry your courage forward into the world.', 'pregnancy'),
('You are the warmth your baby knows. And warmth like yours changes everything.', 'pregnancy'),
('Hold on to the wonder. Even when it''s hard, the wonder is still there.', 'pregnancy'),
('You are mid-miracle. Do not forget it.', 'pregnancy'),
('Your love is already the biggest force in this baby''s world.', 'pregnancy'),
('What you are doing cannot be done any other way. Only you can do this.', 'pregnancy'),
('Today, notice one thing about your body you are grateful for.', 'pregnancy'),
('You are turning ordinary days into the foundation of a whole life.', 'pregnancy'),
('Rest deeply. Dream vividly. Love completely. That is all you need to do.', 'pregnancy'),
('You are becoming. And the becoming is beautiful.', 'pregnancy'),
('Your baby feels everything you feel. Let them feel your peace today.', 'pregnancy'),
('The first chapter of their life is being written in your love. What a story.', 'pregnancy'),
('You are allowed to be scared and certain at the same time.', 'pregnancy'),
('Your body is a place of safety and wonder. Honor it today.', 'pregnancy'),
('You are creating the conditions for a whole lifetime of love.', 'pregnancy'),
('Every day you are pregnant, you are choosing your baby. That is profound.', 'pregnancy'),
('Be proud of how far you have already come.', 'pregnancy'),
('The love that began in your heart will echo for generations.', 'pregnancy'),
('You are on the right path. Every step, even the stumbling ones.', 'pregnancy'),
('There is no manual for this. And you are doing it anyway. That is brave.', 'pregnancy'),
('Your baby needs exactly the mother you already are.', 'pregnancy'),
('The miracle is happening. You are the miracle.', 'pregnancy'),
('Drink water. Take your vitamins. Rest. These are acts of love.', 'pregnancy'),
('You have carried this baby through every storm. That is love.', 'pregnancy'),
('Today, let the fact that you are growing a life fill you with wonder.', 'pregnancy'),
('Every version of you through this pregnancy has been worthy of love.', 'pregnancy'),
('You are in the right story. Keep turning the pages.', 'pregnancy'),
('Even when it is hard to believe it — you are doing magnificently.', 'pregnancy'),
('Your baby is the poem you have been writing your whole life.', 'pregnancy'),
('Everything that feels hard right now is making you into someone extraordinary.', 'pregnancy'),
('You are the home your baby has always known. How beautiful is that?', 'pregnancy'),
('Your love is the thread that holds everything together.', 'pregnancy'),
('What you are building is more than a baby. It is a legacy.', 'pregnancy'),
('You have already made it through 100 percent of your hard days. Keep going.', 'pregnancy'),
('Your presence is the greatest gift your baby will ever receive.', 'pregnancy'),
('The love story of your life is happening right now.', 'pregnancy'),
('You are in the sacred space between who you were and who you are becoming.', 'pregnancy'),
('Let yourself feel wonder today. This is wondrous.', 'pregnancy'),
('You are not behind. You are not failing. You are growing.', 'pregnancy'),
('Your baby''s first experience of the world is being loved by you. That is everything.', 'pregnancy');
